import { AppIntentFamily, AppPack, AppPhrase, AppScenario } from '../contracts';

// Generated by scripts/build-family-pack.ts. Do not edit manually.
const scenarios: AppScenario[] = [
  {
    "id": "coffee-shop",
    "name": "Coffee Shop",
    "emoji": "☕",
    "description": "Order coffee and cafe drinks easily",
    "tip": "Cafe menus often use English terms but a short Tagalog phrase still helps when the shop is busy.",
    "intentFamilies": [
      {
        "id": "tagalog-coffee-shop-1",
        "scenarioId": "coffee-shop",
        "title": "One iced milk coffee please",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-coffee-shop-1",
        "phraseIds": [
          "tagalog-coffee-shop-1"
        ]
      },
      {
        "id": "tagalog-coffee-shop-2",
        "scenarioId": "coffee-shop",
        "title": "I'd like an iced black coffee",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-coffee-shop-2",
        "phraseIds": [
          "tagalog-coffee-shop-2"
        ]
      },
      {
        "id": "tagalog-coffee-shop-3",
        "scenarioId": "coffee-shop",
        "title": "I'd like an iced latte",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-coffee-shop-3",
        "phraseIds": [
          "tagalog-coffee-shop-3"
        ]
      },
      {
        "id": "tagalog-coffee-shop-4",
        "scenarioId": "coffee-shop",
        "title": "Just a little ice",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-coffee-shop-4",
        "phraseIds": [
          "tagalog-coffee-shop-4"
        ]
      },
      {
        "id": "tagalog-coffee-shop-5",
        "scenarioId": "coffee-shop",
        "title": "No sugar please",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-coffee-shop-5",
        "phraseIds": [
          "tagalog-coffee-shop-5"
        ]
      },
      {
        "id": "tagalog-coffee-shop-6",
        "scenarioId": "coffee-shop",
        "title": "For takeaway",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-coffee-shop-6",
        "phraseIds": [
          "tagalog-coffee-shop-6"
        ]
      },
      {
        "id": "tagalog-coffee-shop-7",
        "scenarioId": "coffee-shop",
        "title": "Could I pay, please?",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-coffee-shop-7",
        "phraseIds": [
          "tagalog-coffee-shop-7"
        ]
      }
    ],
    "phrases": [
      {
        "id": "tagalog-coffee-shop-1",
        "scenarioId": "coffee-shop",
        "targetText": "Isang iced coffee na may gatas pakiusap",
        "canonicalTargetText": "Isang iced coffee na may gatas pakiusap",
        "pronunciation": "ee-SAHNG aysd KAW-fee nah may GAH-tas pah-kee-OO-sap",
        "sourceText": "One iced milk coffee please",
        "audioKey": "tagalog-coffee-shop-1",
        "accessTier": "starter",
        "context": "Use this for a classic iced coffee order at a cafe",
        "usageNote": "Use this for a classic iced coffee order at a cafe",
        "intentFamilyId": "tagalog-coffee-shop-1",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "☕"
      },
      {
        "id": "tagalog-coffee-shop-2",
        "scenarioId": "coffee-shop",
        "targetText": "Isang iced black coffee pakiusap",
        "canonicalTargetText": "Isang iced black coffee pakiusap",
        "pronunciation": "ee-SAHNG aysd blak KAW-fee pah-kee-OO-sap",
        "sourceText": "I'd like an iced black coffee",
        "audioKey": "tagalog-coffee-shop-2",
        "accessTier": "starter",
        "context": "Use this when you want coffee without milk",
        "usageNote": "Use this when you want coffee without milk",
        "intentFamilyId": "tagalog-coffee-shop-2",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🧊"
      },
      {
        "id": "tagalog-coffee-shop-3",
        "scenarioId": "coffee-shop",
        "targetText": "Isang iced latte pakiusap",
        "canonicalTargetText": "Isang iced latte pakiusap",
        "pronunciation": "ee-SAHNG aysd LAH-teh pah-kee-OO-sap",
        "sourceText": "I'd like an iced latte",
        "audioKey": "tagalog-coffee-shop-3",
        "accessTier": "starter",
        "context": "Helpful when ordering a familiar milk coffee drink",
        "usageNote": "Helpful when ordering a familiar milk coffee drink",
        "intentFamilyId": "tagalog-coffee-shop-3",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🥛"
      },
      {
        "id": "tagalog-coffee-shop-4",
        "scenarioId": "coffee-shop",
        "targetText": "Kaunting yelo lang",
        "canonicalTargetText": "Kaunting yelo lang",
        "pronunciation": "kah-OON-ting YEH-loh lahng",
        "sourceText": "Just a little ice",
        "audioKey": "tagalog-coffee-shop-4",
        "accessTier": "starter",
        "context": "Add this when you want less ice in your drink",
        "usageNote": "Add this when you want less ice in your drink",
        "intentFamilyId": "tagalog-coffee-shop-4",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🧊"
      },
      {
        "id": "tagalog-coffee-shop-5",
        "scenarioId": "coffee-shop",
        "targetText": "Walang asukal pakiusap",
        "canonicalTargetText": "Walang asukal pakiusap",
        "pronunciation": "WAH-lang ah-SOO-kal pah-kee-OO-sap",
        "sourceText": "No sugar please",
        "audioKey": "tagalog-coffee-shop-5",
        "accessTier": "starter",
        "context": "Use this to keep your drink less sweet",
        "usageNote": "Use this to keep your drink less sweet",
        "intentFamilyId": "tagalog-coffee-shop-5",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🚫"
      },
      {
        "id": "tagalog-coffee-shop-6",
        "scenarioId": "coffee-shop",
        "targetText": "Takeout po",
        "canonicalTargetText": "Takeout po",
        "pronunciation": "TEYK-awt poh",
        "sourceText": "For takeaway",
        "audioKey": "tagalog-coffee-shop-6",
        "accessTier": "starter",
        "context": "Say this when you want takeaway instead of staying",
        "usageNote": "Say this when you want takeaway instead of staying",
        "intentFamilyId": "tagalog-coffee-shop-6",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🥤"
      },
      {
        "id": "tagalog-coffee-shop-7",
        "scenarioId": "coffee-shop",
        "targetText": "Magbabayad na ako",
        "canonicalTargetText": "Magbabayad na ako",
        "pronunciation": "mag-bah-bah-YAD nah ah-KOH",
        "sourceText": "Could I pay, please?",
        "audioKey": "tagalog-coffee-shop-7",
        "accessTier": "starter",
        "context": "Use this when you are ready to pay or ask for the bill",
        "usageNote": "Use this when you are ready to pay or ask for the bill",
        "intentFamilyId": "tagalog-coffee-shop-7",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "💵"
      }
    ]
  },
  {
    "id": "street-food",
    "name": "Street Food / Restaurant",
    "emoji": "🍜",
    "description": "Order fast and eat well",
    "tip": "Pointing helps at busy stalls but simple Tagalog is useful for spice level water and takeout.",
    "intentFamilies": [
      {
        "id": "tagalog-street-food-1",
        "scenarioId": "street-food",
        "title": "One portion please",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-street-food-1",
        "phraseIds": [
          "tagalog-street-food-1"
        ]
      },
      {
        "id": "tagalog-street-food-2",
        "scenarioId": "street-food",
        "title": "I'll take this bowl",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-street-food-2",
        "phraseIds": [
          "tagalog-street-food-2"
        ]
      },
      {
        "id": "tagalog-street-food-3",
        "scenarioId": "street-food",
        "title": "Not spicy, please",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-street-food-3",
        "phraseIds": [
          "tagalog-street-food-3"
        ]
      },
      {
        "id": "tagalog-street-food-4",
        "scenarioId": "street-food",
        "title": "More herbs please",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-street-food-4",
        "phraseIds": [
          "tagalog-street-food-4"
        ]
      },
      {
        "id": "tagalog-street-food-5",
        "scenarioId": "street-food",
        "title": "Do you have bottled water",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-street-food-5",
        "phraseIds": [
          "tagalog-street-food-5"
        ]
      },
      {
        "id": "tagalog-street-food-6",
        "scenarioId": "street-food",
        "title": "A spoon and chopsticks please",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-street-food-6",
        "phraseIds": [
          "tagalog-street-food-6"
        ]
      },
      {
        "id": "tagalog-street-food-7",
        "scenarioId": "street-food",
        "title": "Please pack this to go",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-street-food-7",
        "phraseIds": [
          "tagalog-street-food-7"
        ]
      }
    ],
    "phrases": [
      {
        "id": "tagalog-street-food-1",
        "scenarioId": "street-food",
        "targetText": "Isang order pakiusap",
        "canonicalTargetText": "Isang order pakiusap",
        "pronunciation": "ee-SAHNG OR-der pah-kee-OO-sap",
        "sourceText": "One portion please",
        "audioKey": "tagalog-street-food-1",
        "accessTier": "starter",
        "context": "Use this for a simple food order while pointing",
        "usageNote": "Use this for a simple food order while pointing",
        "intentFamilyId": "tagalog-street-food-1",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🍽️"
      },
      {
        "id": "tagalog-street-food-2",
        "scenarioId": "street-food",
        "targetText": "Ito na lang ang kukunin ko",
        "canonicalTargetText": "Ito na lang ang kukunin ko",
        "pronunciation": "ee-TOH nah lahng ang koo-KOO-nin koh",
        "sourceText": "I'll take this bowl",
        "audioKey": "tagalog-street-food-2",
        "accessTier": "starter",
        "context": "Use this while pointing at the bowl or plate you want",
        "usageNote": "Use this while pointing at the bowl or plate you want",
        "intentFamilyId": "tagalog-street-food-2",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🍜"
      },
      {
        "id": "tagalog-street-food-3",
        "scenarioId": "street-food",
        "targetText": "Hindi maanghang pakiusap",
        "canonicalTargetText": "Hindi maanghang pakiusap",
        "pronunciation": "hin-DEE mah-ANG-hang pah-kee-OO-sap",
        "sourceText": "Not spicy, please",
        "audioKey": "tagalog-street-food-3",
        "accessTier": "starter",
        "context": "Use this before the dish is prepared if you want mild food",
        "usageNote": "Use this before the dish is prepared if you want mild food",
        "intentFamilyId": "tagalog-street-food-3",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🌶️"
      },
      {
        "id": "tagalog-street-food-4",
        "scenarioId": "street-food",
        "targetText": "Dagdagan ng gulay pakiusap",
        "canonicalTargetText": "Dagdagan ng gulay pakiusap",
        "pronunciation": "dag-DAH-gan nang goo-LAHY pah-kee-OO-sap",
        "sourceText": "More herbs please",
        "audioKey": "tagalog-street-food-4",
        "accessTier": "starter",
        "context": "Use this when you want extra greens or garnish",
        "usageNote": "Use this when you want extra greens or garnish",
        "intentFamilyId": "tagalog-street-food-4",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🥬"
      },
      {
        "id": "tagalog-street-food-5",
        "scenarioId": "street-food",
        "targetText": "May bottled water ba kayo",
        "canonicalTargetText": "May bottled water ba kayo",
        "pronunciation": "may BOT-ld WAH-ter bah kah-YOH",
        "sourceText": "Do you have bottled water",
        "audioKey": "tagalog-street-food-5",
        "accessTier": "starter",
        "context": "Ask this when you want bottled water with your meal",
        "usageNote": "Ask this when you want bottled water with your meal",
        "intentFamilyId": "tagalog-street-food-5",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "💧"
      },
      {
        "id": "tagalog-street-food-6",
        "scenarioId": "street-food",
        "targetText": "Kutsara at chopsticks pakiusap",
        "canonicalTargetText": "Kutsara at chopsticks pakiusap",
        "pronunciation": "koots-AH-rah at CHOP-stiks pah-kee-OO-sap",
        "sourceText": "A spoon and chopsticks please",
        "audioKey": "tagalog-street-food-6",
        "accessTier": "starter",
        "context": "Use this if utensils were not set out",
        "usageNote": "Use this if utensils were not set out",
        "intentFamilyId": "tagalog-street-food-6",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🥢"
      },
      {
        "id": "tagalog-street-food-7",
        "scenarioId": "street-food",
        "targetText": "Pabalot na lang pakiusap",
        "canonicalTargetText": "Pabalot na lang pakiusap",
        "pronunciation": "pah-bah-LOT nah lahng pah-kee-OO-sap",
        "sourceText": "Please pack this to go",
        "audioKey": "tagalog-street-food-7",
        "accessTier": "starter",
        "context": "Say this when you want takeaway from a stall or restaurant",
        "usageNote": "Say this when you want takeaway from a stall or restaurant",
        "intentFamilyId": "tagalog-street-food-7",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🛍️"
      }
    ]
  },
  {
    "id": "grab-taxi",
    "name": "Grab / Taxi",
    "emoji": "🚕",
    "description": "Get around without confusion",
    "tip": "Grab is common in major cities and showing the destination on your phone helps drivers quickly.",
    "intentFamilies": [
      {
        "id": "tagalog-grab-taxi-1",
        "scenarioId": "grab-taxi",
        "title": "Please take me here",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-grab-taxi-1",
        "phraseIds": [
          "tagalog-grab-taxi-1"
        ]
      },
      {
        "id": "tagalog-grab-taxi-2",
        "scenarioId": "grab-taxi",
        "title": "Go to Makati",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-grab-taxi-2",
        "phraseIds": [
          "tagalog-grab-taxi-2"
        ]
      },
      {
        "id": "tagalog-grab-taxi-3",
        "scenarioId": "grab-taxi",
        "title": "You can stop here",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-grab-taxi-3",
        "phraseIds": [
          "tagalog-grab-taxi-3"
        ]
      },
      {
        "id": "tagalog-grab-taxi-4",
        "scenarioId": "grab-taxi",
        "title": "Go this way",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-grab-taxi-4",
        "phraseIds": [
          "tagalog-grab-taxi-4"
        ]
      },
      {
        "id": "tagalog-grab-taxi-5",
        "scenarioId": "grab-taxi",
        "title": "Please turn on the air conditioning",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-grab-taxi-5",
        "phraseIds": [
          "tagalog-grab-taxi-5"
        ]
      },
      {
        "id": "tagalog-grab-taxi-6",
        "scenarioId": "grab-taxi",
        "title": "Wait for me five minutes",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-grab-taxi-6",
        "phraseIds": [
          "tagalog-grab-taxi-6"
        ]
      },
      {
        "id": "tagalog-grab-taxi-7",
        "scenarioId": "grab-taxi",
        "title": "I'll pay in cash",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-grab-taxi-7",
        "phraseIds": [
          "tagalog-grab-taxi-7"
        ]
      }
    ],
    "phrases": [
      {
        "id": "tagalog-grab-taxi-1",
        "scenarioId": "grab-taxi",
        "targetText": "Pakihatid ako rito",
        "canonicalTargetText": "Pakihatid ako rito",
        "pronunciation": "pah-kee-HA-tid ah-KOH ree-TOH",
        "sourceText": "Please take me here",
        "audioKey": "tagalog-grab-taxi-1",
        "accessTier": "starter",
        "context": "Use this while showing your destination on your phone",
        "usageNote": "Use this while showing your destination on your phone",
        "intentFamilyId": "tagalog-grab-taxi-1",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "📍"
      },
      {
        "id": "tagalog-grab-taxi-2",
        "scenarioId": "grab-taxi",
        "targetText": "Punta tayo sa Makati",
        "canonicalTargetText": "Punta tayo sa Makati",
        "pronunciation": "POON-tah tah-YOH sah mah-KAH-tee",
        "sourceText": "Go to Makati",
        "audioKey": "tagalog-grab-taxi-2",
        "accessTier": "starter",
        "context": "Use this for a simple destination in the city",
        "usageNote": "Use this for a simple destination in the city",
        "intentFamilyId": "tagalog-grab-taxi-2",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🏙️"
      },
      {
        "id": "tagalog-grab-taxi-3",
        "scenarioId": "grab-taxi",
        "targetText": "Dito na lang po",
        "canonicalTargetText": "Dito na lang po",
        "pronunciation": "dee-TOH nah lahng poh",
        "sourceText": "You can stop here",
        "audioKey": "tagalog-grab-taxi-3",
        "accessTier": "starter",
        "context": "Use this when you want the driver to stop at the current spot",
        "usageNote": "Use this when you want the driver to stop at the current spot",
        "intentFamilyId": "tagalog-grab-taxi-3",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🛑"
      },
      {
        "id": "tagalog-grab-taxi-4",
        "scenarioId": "grab-taxi",
        "targetText": "Dito po tayo dumaan",
        "canonicalTargetText": "Dito po tayo dumaan",
        "pronunciation": "dee-TOH poh tah-YOH doo-MAH-an",
        "sourceText": "Go this way",
        "audioKey": "tagalog-grab-taxi-4",
        "accessTier": "starter",
        "context": "Use this if you need to guide the driver",
        "usageNote": "Use this if you need to guide the driver",
        "intentFamilyId": "tagalog-grab-taxi-4",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "➡️"
      },
      {
        "id": "tagalog-grab-taxi-5",
        "scenarioId": "grab-taxi",
        "targetText": "Paki-on ang aircon pakiusap",
        "canonicalTargetText": "Paki-on ang aircon pakiusap",
        "pronunciation": "pah-kee ON ang AIR-kon pah-kee-OO-sap",
        "sourceText": "Please turn on the air conditioning",
        "audioKey": "tagalog-grab-taxi-5",
        "accessTier": "starter",
        "context": "Use this on a hot ride if the aircon is off",
        "usageNote": "Use this on a hot ride if the aircon is off",
        "intentFamilyId": "tagalog-grab-taxi-5",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "❄️"
      },
      {
        "id": "tagalog-grab-taxi-6",
        "scenarioId": "grab-taxi",
        "targetText": "Hintayin nyo ako ng limang minuto",
        "canonicalTargetText": "Hintayin nyo ako ng limang minuto",
        "pronunciation": "hin-TAH-yin nyoh ah-KOH nang lee-MAHNG mee-NOO-toh",
        "sourceText": "Wait for me five minutes",
        "audioKey": "tagalog-grab-taxi-6",
        "accessTier": "starter",
        "context": "Use this if you need a very short stop",
        "usageNote": "Use this if you need a very short stop",
        "intentFamilyId": "tagalog-grab-taxi-6",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "⏳"
      },
      {
        "id": "tagalog-grab-taxi-7",
        "scenarioId": "grab-taxi",
        "targetText": "Cash ang bayad ko",
        "canonicalTargetText": "Cash ang bayad ko",
        "pronunciation": "kash ang BAH-yad koh",
        "sourceText": "I'll pay in cash",
        "audioKey": "tagalog-grab-taxi-7",
        "accessTier": "starter",
        "context": "Use this when payment method needs to be clear in the ride or at a small counter",
        "usageNote": "Use this when payment method needs to be clear in the ride or at a small counter",
        "intentFamilyId": "tagalog-grab-taxi-7",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "💵"
      }
    ]
  },
  {
    "id": "asking-price",
    "name": "Asking the Price",
    "emoji": "💸",
    "description": "Check prices before you buy",
    "tip": "Ask the price before agreeing and keep small bills ready when shopping at markets or street stalls.",
    "intentFamilies": [
      {
        "id": "tagalog-asking-price-1",
        "scenarioId": "asking-price",
        "title": "How much is this?",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-asking-price-1",
        "phraseIds": [
          "tagalog-asking-price-1"
        ]
      },
      {
        "id": "tagalog-asking-price-2",
        "scenarioId": "asking-price",
        "title": "How much per kilo",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-asking-price-2",
        "phraseIds": [
          "tagalog-asking-price-2"
        ]
      },
      {
        "id": "tagalog-asking-price-3",
        "scenarioId": "asking-price",
        "title": "Too expensive",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-asking-price-3",
        "phraseIds": [
          "tagalog-asking-price-3"
        ]
      },
      {
        "id": "tagalog-asking-price-4",
        "scenarioId": "asking-price",
        "title": "Can you lower it a little",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-asking-price-4",
        "phraseIds": [
          "tagalog-asking-price-4"
        ]
      },
      {
        "id": "tagalog-asking-price-5",
        "scenarioId": "asking-price",
        "title": "What's your final price",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-asking-price-5",
        "phraseIds": [
          "tagalog-asking-price-5"
        ]
      },
      {
        "id": "tagalog-asking-price-6",
        "scenarioId": "asking-price",
        "title": "Please show me another one",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-asking-price-6",
        "phraseIds": [
          "tagalog-asking-price-6"
        ]
      },
      {
        "id": "tagalog-asking-price-7",
        "scenarioId": "asking-price",
        "title": "I'll take this one",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-asking-price-7",
        "phraseIds": [
          "tagalog-asking-price-7"
        ]
      }
    ],
    "phrases": [
      {
        "id": "tagalog-asking-price-1",
        "scenarioId": "asking-price",
        "targetText": "Magkano ito",
        "canonicalTargetText": "Magkano ito",
        "pronunciation": "mag-KAH-noh ee-TOH",
        "sourceText": "How much is this?",
        "audioKey": "tagalog-asking-price-1",
        "accessTier": "starter",
        "context": "Use this while pointing at an item",
        "usageNote": "Use this while pointing at an item",
        "intentFamilyId": "tagalog-asking-price-1",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🏷️"
      },
      {
        "id": "tagalog-asking-price-2",
        "scenarioId": "asking-price",
        "targetText": "Magkano kada kilo",
        "canonicalTargetText": "Magkano kada kilo",
        "pronunciation": "mag-KAH-noh KAH-dah KEE-loh",
        "sourceText": "How much per kilo",
        "audioKey": "tagalog-asking-price-2",
        "accessTier": "starter",
        "context": "Use this for fruit snacks or anything sold by weight",
        "usageNote": "Use this for fruit snacks or anything sold by weight",
        "intentFamilyId": "tagalog-asking-price-2",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "⚖️"
      },
      {
        "id": "tagalog-asking-price-3",
        "scenarioId": "asking-price",
        "targetText": "Masyadong mahal",
        "canonicalTargetText": "Masyadong mahal",
        "pronunciation": "mahs-YAH-dohng mah-HAL",
        "sourceText": "Too expensive",
        "audioKey": "tagalog-asking-price-3",
        "accessTier": "starter",
        "context": "Say this lightly when reacting to a high price",
        "usageNote": "Say this lightly when reacting to a high price",
        "intentFamilyId": "tagalog-asking-price-3",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "😅"
      },
      {
        "id": "tagalog-asking-price-4",
        "scenarioId": "asking-price",
        "targetText": "Puwede bang tawaran nang kaunti",
        "canonicalTargetText": "Puwede bang tawaran nang kaunti",
        "pronunciation": "poo-WEH-deh bahng tah-WAH-ran nang kah-OON-tee",
        "sourceText": "Can you lower it a little",
        "audioKey": "tagalog-asking-price-4",
        "accessTier": "starter",
        "context": "Use this politely when bargaining is normal",
        "usageNote": "Use this politely when bargaining is normal",
        "intentFamilyId": "tagalog-asking-price-4",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🤝"
      },
      {
        "id": "tagalog-asking-price-5",
        "scenarioId": "asking-price",
        "targetText": "Ano ang huling presyo ninyo",
        "canonicalTargetText": "Ano ang huling presyo ninyo",
        "pronunciation": "AH-noh ang HOO-ling PRES-yoh nee-NYOH",
        "sourceText": "What's your final price",
        "audioKey": "tagalog-asking-price-5",
        "accessTier": "starter",
        "context": "Ask this before making a final decision",
        "usageNote": "Ask this before making a final decision",
        "intentFamilyId": "tagalog-asking-price-5",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "💬"
      },
      {
        "id": "tagalog-asking-price-6",
        "scenarioId": "asking-price",
        "targetText": "Pakipakita po ang isa pa",
        "canonicalTargetText": "Pakipakita po ang isa pa",
        "pronunciation": "pah-kee-pah-KEE-tah poh ang EE-sah pah",
        "sourceText": "Please show me another one",
        "audioKey": "tagalog-asking-price-6",
        "accessTier": "starter",
        "context": "Use this when you want to compare options",
        "usageNote": "Use this when you want to compare options",
        "intentFamilyId": "tagalog-asking-price-6",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "👀"
      },
      {
        "id": "tagalog-asking-price-7",
        "scenarioId": "asking-price",
        "targetText": "Ito ang kukunin ko",
        "canonicalTargetText": "Ito ang kukunin ko",
        "pronunciation": "ee-TOH ang koo-KOO-nin koh",
        "sourceText": "I'll take this one",
        "audioKey": "tagalog-asking-price-7",
        "accessTier": "starter",
        "context": "Say this once you agree on the item and price",
        "usageNote": "Say this once you agree on the item and price",
        "intentFamilyId": "tagalog-asking-price-7",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🛍️"
      }
    ]
  },
  {
    "id": "polite-basics",
    "name": "Polite Basics",
    "emoji": "🙏",
    "description": "Be polite in everyday moments",
    "tip": "A warm tone and a simple greeting go a long way in hotels shops rides and casual conversations.",
    "intentFamilies": [
      {
        "id": "tagalog-polite-basics-1",
        "scenarioId": "polite-basics",
        "title": "Hello",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-polite-basics-1",
        "phraseIds": [
          "tagalog-polite-basics-1"
        ]
      },
      {
        "id": "tagalog-polite-basics-2",
        "scenarioId": "polite-basics",
        "title": "Thank you",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-polite-basics-2",
        "phraseIds": [
          "tagalog-polite-basics-2"
        ]
      },
      {
        "id": "tagalog-polite-basics-3",
        "scenarioId": "polite-basics",
        "title": "Yes, respectfully / I understand",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-polite-basics-3",
        "phraseIds": [
          "tagalog-polite-basics-3"
        ]
      },
      {
        "id": "tagalog-polite-basics-4",
        "scenarioId": "polite-basics",
        "title": "No thanks, I'm okay",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-polite-basics-4",
        "phraseIds": [
          "tagalog-polite-basics-4"
        ]
      },
      {
        "id": "tagalog-polite-basics-5",
        "scenarioId": "polite-basics",
        "title": "Excuse me",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-polite-basics-5",
        "phraseIds": [
          "tagalog-polite-basics-5"
        ]
      },
      {
        "id": "tagalog-polite-basics-6",
        "scenarioId": "polite-basics",
        "title": "It's okay",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-polite-basics-6",
        "phraseIds": [
          "tagalog-polite-basics-6"
        ]
      },
      {
        "id": "tagalog-polite-basics-7",
        "scenarioId": "polite-basics",
        "title": "Goodbye",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-polite-basics-7",
        "phraseIds": [
          "tagalog-polite-basics-7"
        ]
      }
    ],
    "phrases": [
      {
        "id": "tagalog-polite-basics-1",
        "scenarioId": "polite-basics",
        "targetText": "Kumusta",
        "canonicalTargetText": "Kumusta",
        "pronunciation": "koo-MOOS-tah",
        "sourceText": "Hello",
        "audioKey": "tagalog-polite-basics-1",
        "accessTier": "starter",
        "context": "Use this to greet people in casual travel moments",
        "usageNote": "Use this to greet people in casual travel moments",
        "intentFamilyId": "tagalog-polite-basics-1",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "👋"
      },
      {
        "id": "tagalog-polite-basics-2",
        "scenarioId": "polite-basics",
        "targetText": "Salamat",
        "canonicalTargetText": "Salamat",
        "pronunciation": "sah-LAH-mat",
        "sourceText": "Thank you",
        "audioKey": "tagalog-polite-basics-2",
        "accessTier": "starter",
        "context": "Say this anytime someone helps you",
        "usageNote": "Say this anytime someone helps you",
        "intentFamilyId": "tagalog-polite-basics-2",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🙏"
      },
      {
        "id": "tagalog-polite-basics-3",
        "scenarioId": "polite-basics",
        "targetText": "Opo",
        "canonicalTargetText": "Opo",
        "pronunciation": "OH-poh",
        "sourceText": "Yes, respectfully / I understand",
        "audioKey": "tagalog-polite-basics-3",
        "accessTier": "starter",
        "context": "Use this as a respectful yes or acknowledgment when replying to someone older or in a service exchange",
        "usageNote": "Use this as a respectful yes or acknowledgment when replying to someone older or in a service exchange",
        "intentFamilyId": "tagalog-polite-basics-3",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🙂"
      },
      {
        "id": "tagalog-polite-basics-4",
        "scenarioId": "polite-basics",
        "targetText": "Ayos lang salamat",
        "canonicalTargetText": "Ayos lang salamat",
        "pronunciation": "AH-yos lahng sah-LAH-mat",
        "sourceText": "No thanks, I'm okay",
        "audioKey": "tagalog-polite-basics-4",
        "accessTier": "starter",
        "context": "Use this to politely decline an offer or sales approach",
        "usageNote": "Use this to politely decline an offer or sales approach",
        "intentFamilyId": "tagalog-polite-basics-4",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🙅"
      },
      {
        "id": "tagalog-polite-basics-5",
        "scenarioId": "polite-basics",
        "targetText": "Paumanhin",
        "canonicalTargetText": "Paumanhin",
        "pronunciation": "pah-oo-MAN-hin",
        "sourceText": "Excuse me",
        "audioKey": "tagalog-polite-basics-5",
        "accessTier": "starter",
        "context": "Use this to get attention politely first or to apologize briefly if needed",
        "usageNote": "Use this to get attention politely first or to apologize briefly if needed",
        "intentFamilyId": "tagalog-polite-basics-5",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🙏"
      },
      {
        "id": "tagalog-polite-basics-6",
        "scenarioId": "polite-basics",
        "targetText": "Ayos lang",
        "canonicalTargetText": "Ayos lang",
        "pronunciation": "AH-yos lahng",
        "sourceText": "It's okay",
        "audioKey": "tagalog-polite-basics-6",
        "accessTier": "starter",
        "context": "Say this when someone apologizes to you",
        "usageNote": "Say this when someone apologizes to you",
        "intentFamilyId": "tagalog-polite-basics-6",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "👌"
      },
      {
        "id": "tagalog-polite-basics-7",
        "scenarioId": "polite-basics",
        "targetText": "Paalam",
        "canonicalTargetText": "Paalam",
        "pronunciation": "pah-AH-lam",
        "sourceText": "Goodbye",
        "audioKey": "tagalog-polite-basics-7",
        "accessTier": "starter",
        "context": "Use this when leaving a shop hotel or ride",
        "usageNote": "Use this when leaving a shop hotel or ride",
        "intentFamilyId": "tagalog-polite-basics-7",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "👋"
      }
    ]
  },
  {
    "id": "convenience-store",
    "name": "Convenience Store",
    "emoji": "🏪",
    "description": "Handle quick shop stops",
    "tip": "Mini-marts are good for water tissues sunscreen and quick snacks during a long day out.",
    "intentFamilies": [
      {
        "id": "tagalog-convenience-store-1",
        "scenarioId": "convenience-store",
        "title": "A bottle of water, please",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-convenience-store-1",
        "phraseIds": [
          "tagalog-convenience-store-1"
        ]
      },
      {
        "id": "tagalog-convenience-store-2",
        "scenarioId": "convenience-store",
        "title": "Do you have a bag",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-convenience-store-2",
        "phraseIds": [
          "tagalog-convenience-store-2"
        ]
      },
      {
        "id": "tagalog-convenience-store-3",
        "scenarioId": "convenience-store",
        "title": "Tissues please",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-convenience-store-3",
        "phraseIds": [
          "tagalog-convenience-store-3"
        ]
      },
      {
        "id": "tagalog-convenience-store-4",
        "scenarioId": "convenience-store",
        "title": "Where is the sunscreen",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-convenience-store-4",
        "phraseIds": [
          "tagalog-convenience-store-4"
        ]
      },
      {
        "id": "tagalog-convenience-store-5",
        "scenarioId": "convenience-store",
        "title": "Please open this for me",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-convenience-store-5",
        "phraseIds": [
          "tagalog-convenience-store-5"
        ]
      },
      {
        "id": "tagalog-convenience-store-6",
        "scenarioId": "convenience-store",
        "title": "Can I pay by card?",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-convenience-store-6",
        "phraseIds": [
          "tagalog-convenience-store-6"
        ]
      },
      {
        "id": "tagalog-convenience-store-7",
        "scenarioId": "convenience-store",
        "title": "Please give me the receipt",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-convenience-store-7",
        "phraseIds": [
          "tagalog-convenience-store-7"
        ]
      }
    ],
    "phrases": [
      {
        "id": "tagalog-convenience-store-1",
        "scenarioId": "convenience-store",
        "targetText": "Isang bote ng tubig, pakiusap",
        "canonicalTargetText": "Isang bote ng tubig, pakiusap",
        "pronunciation": "ee-SAHNG BOH-teh nang too-BIG pah-kee-OO-sap",
        "sourceText": "A bottle of water, please",
        "audioKey": "tagalog-convenience-store-1",
        "accessTier": "starter",
        "context": "Use this for a quick water purchase",
        "usageNote": "Use this for a quick water purchase",
        "intentFamilyId": "tagalog-convenience-store-1",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "💧"
      },
      {
        "id": "tagalog-convenience-store-2",
        "scenarioId": "convenience-store",
        "targetText": "May supot ba kayo",
        "canonicalTargetText": "May supot ba kayo",
        "pronunciation": "may SOO-pot bah kah-YOH",
        "sourceText": "Do you have a bag",
        "audioKey": "tagalog-convenience-store-2",
        "accessTier": "starter",
        "context": "Ask this if you need a carry bag",
        "usageNote": "Ask this if you need a carry bag",
        "intentFamilyId": "tagalog-convenience-store-2",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🛍️"
      },
      {
        "id": "tagalog-convenience-store-3",
        "scenarioId": "convenience-store",
        "targetText": "Tisyu pakiusap",
        "canonicalTargetText": "Tisyu pakiusap",
        "pronunciation": "TEE-shoo pah-kee-OO-sap",
        "sourceText": "Tissues please",
        "audioKey": "tagalog-convenience-store-3",
        "accessTier": "starter",
        "context": "Use this when you need tissues at the counter",
        "usageNote": "Use this when you need tissues at the counter",
        "intentFamilyId": "tagalog-convenience-store-3",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🧻"
      },
      {
        "id": "tagalog-convenience-store-4",
        "scenarioId": "convenience-store",
        "targetText": "Nasaan ang sunscreen",
        "canonicalTargetText": "Nasaan ang sunscreen",
        "pronunciation": "nah-SAH-an ang SUN-skreen",
        "sourceText": "Where is the sunscreen",
        "audioKey": "tagalog-convenience-store-4",
        "accessTier": "starter",
        "context": "Ask this when you need help finding sunscreen",
        "usageNote": "Ask this when you need help finding sunscreen",
        "intentFamilyId": "tagalog-convenience-store-4",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🧴"
      },
      {
        "id": "tagalog-convenience-store-5",
        "scenarioId": "convenience-store",
        "targetText": "Pabukas nito pakiusap",
        "canonicalTargetText": "Pabukas nito pakiusap",
        "pronunciation": "pah-BOO-kas NEE-toh pah-kee-OO-sap",
        "sourceText": "Please open this for me",
        "audioKey": "tagalog-convenience-store-5",
        "accessTier": "starter",
        "context": "Use this for bottled drinks or hard packaging",
        "usageNote": "Use this for bottled drinks or hard packaging",
        "intentFamilyId": "tagalog-convenience-store-5",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🔓"
      },
      {
        "id": "tagalog-convenience-store-6",
        "scenarioId": "convenience-store",
        "targetText": "Puwede bang magbayad gamit ang card",
        "canonicalTargetText": "Puwede bang magbayad gamit ang card",
        "pronunciation": "poo-WEH-deh bahng mag-bah-YAD gah-mit ang kard",
        "sourceText": "Can I pay by card?",
        "audioKey": "tagalog-convenience-store-6",
        "accessTier": "starter",
        "context": "Ask this before checkout if you are short on cash",
        "usageNote": "Ask this before checkout if you are short on cash",
        "intentFamilyId": "tagalog-convenience-store-6",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "💳"
      },
      {
        "id": "tagalog-convenience-store-7",
        "scenarioId": "convenience-store",
        "targetText": "Pahingi ng resibo pakiusap",
        "canonicalTargetText": "Pahingi ng resibo pakiusap",
        "pronunciation": "pah-HING-ee nang reh-SEE-bo pah-kee-OO-sap",
        "sourceText": "Please give me the receipt",
        "audioKey": "tagalog-convenience-store-7",
        "accessTier": "starter",
        "context": "Use this if you need the receipt for your purchase",
        "usageNote": "Use this if you need the receipt for your purchase",
        "intentFamilyId": "tagalog-convenience-store-7",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🧾"
      }
    ]
  },
  {
    "id": "hotel-hostel",
    "name": "Hotel / Hostel",
    "emoji": "🏨",
    "description": "Handle check-in and room needs",
    "tip": "Keep your passport and booking details ready because front desks usually register guests at check-in.",
    "intentFamilies": [
      {
        "id": "tagalog-hotel-hostel-1",
        "scenarioId": "hotel-hostel",
        "title": "I have a reservation",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-hotel-hostel-1",
        "phraseIds": [
          "tagalog-hotel-hostel-1"
        ]
      },
      {
        "id": "tagalog-hotel-hostel-2",
        "scenarioId": "hotel-hostel",
        "title": "I'd like to check in",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-hotel-hostel-2",
        "phraseIds": [
          "tagalog-hotel-hostel-2"
        ]
      },
      {
        "id": "tagalog-hotel-hostel-3",
        "scenarioId": "hotel-hostel",
        "title": "What time is check-out",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-hotel-hostel-3",
        "phraseIds": [
          "tagalog-hotel-hostel-3"
        ]
      },
      {
        "id": "tagalog-hotel-hostel-4",
        "scenarioId": "hotel-hostel",
        "title": "This room is too hot",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-hotel-hostel-4",
        "phraseIds": [
          "tagalog-hotel-hostel-4"
        ]
      },
      {
        "id": "tagalog-hotel-hostel-5",
        "scenarioId": "hotel-hostel",
        "title": "The air conditioning isn't working",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-hotel-hostel-5",
        "phraseIds": [
          "tagalog-hotel-hostel-5"
        ]
      },
      {
        "id": "tagalog-hotel-hostel-6",
        "scenarioId": "hotel-hostel",
        "title": "More towels please",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-hotel-hostel-6",
        "phraseIds": [
          "tagalog-hotel-hostel-6"
        ]
      },
      {
        "id": "tagalog-hotel-hostel-7",
        "scenarioId": "hotel-hostel",
        "title": "Please hold my luggage",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-hotel-hostel-7",
        "phraseIds": [
          "tagalog-hotel-hostel-7"
        ]
      }
    ],
    "phrases": [
      {
        "id": "tagalog-hotel-hostel-1",
        "scenarioId": "hotel-hostel",
        "targetText": "May reservation ako",
        "canonicalTargetText": "May reservation ako",
        "pronunciation": "may reh-zur-VAY-shon ah-KOH",
        "sourceText": "I have a reservation",
        "audioKey": "tagalog-hotel-hostel-1",
        "accessTier": "starter",
        "context": "Use this first at reception while showing your booking details",
        "usageNote": "Use this first at reception while showing your booking details",
        "intentFamilyId": "tagalog-hotel-hostel-1",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🛎️"
      },
      {
        "id": "tagalog-hotel-hostel-2",
        "scenarioId": "hotel-hostel",
        "targetText": "Mag-check in po ako",
        "canonicalTargetText": "Mag-check in po ako",
        "pronunciation": "mag-CHECK in poh ah-KOH",
        "sourceText": "I'd like to check in",
        "audioKey": "tagalog-hotel-hostel-2",
        "accessTier": "starter",
        "context": "Say this when you are ready to start the arrival check in process",
        "usageNote": "Say this when you are ready to start the arrival check in process",
        "intentFamilyId": "tagalog-hotel-hostel-2",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🔑"
      },
      {
        "id": "tagalog-hotel-hostel-3",
        "scenarioId": "hotel-hostel",
        "targetText": "Anong oras ang check-out",
        "canonicalTargetText": "Anong oras ang check-out",
        "pronunciation": "AH-nong OH-ras ang check-awt",
        "sourceText": "What time is check-out",
        "audioKey": "tagalog-hotel-hostel-3",
        "accessTier": "starter",
        "context": "Ask this early so you know the departure time",
        "usageNote": "Ask this early so you know the departure time",
        "intentFamilyId": "tagalog-hotel-hostel-3",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "⏰"
      },
      {
        "id": "tagalog-hotel-hostel-4",
        "scenarioId": "hotel-hostel",
        "targetText": "Masyadong mainit ang kuwartong ito",
        "canonicalTargetText": "Masyadong mainit ang kuwartong ito",
        "pronunciation": "mahs-YAH-dohng mah-EE-nit ang kwar-TONG ee-TOH",
        "sourceText": "This room is too hot",
        "audioKey": "tagalog-hotel-hostel-4",
        "accessTier": "starter",
        "context": "Use this if the room feels too warm",
        "usageNote": "Use this if the room feels too warm",
        "intentFamilyId": "tagalog-hotel-hostel-4",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🥵"
      },
      {
        "id": "tagalog-hotel-hostel-5",
        "scenarioId": "hotel-hostel",
        "targetText": "Hindi gumagana ang aircon",
        "canonicalTargetText": "Hindi gumagana ang aircon",
        "pronunciation": "hin-DEE goo-ma-GAH-na ang AIR-kon",
        "sourceText": "The air conditioning isn't working",
        "audioKey": "tagalog-hotel-hostel-5",
        "accessTier": "starter",
        "context": "Say this when you need staff to check the AC in your room",
        "usageNote": "Say this when you need staff to check the AC in your room",
        "intentFamilyId": "tagalog-hotel-hostel-5",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "❄️"
      },
      {
        "id": "tagalog-hotel-hostel-6",
        "scenarioId": "hotel-hostel",
        "targetText": "Pahingi pa ng tuwalya pakiusap",
        "canonicalTargetText": "Pahingi pa ng tuwalya pakiusap",
        "pronunciation": "pah-HING-ee pah nang too-WAL-yah pah-kee-OO-sap",
        "sourceText": "More towels please",
        "audioKey": "tagalog-hotel-hostel-6",
        "accessTier": "starter",
        "context": "Use this when you need extra towels",
        "usageNote": "Use this when you need extra towels",
        "intentFamilyId": "tagalog-hotel-hostel-6",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🧺"
      },
      {
        "id": "tagalog-hotel-hostel-7",
        "scenarioId": "hotel-hostel",
        "targetText": "Pakitago muna ang bagahe ko",
        "canonicalTargetText": "Pakitago muna ang bagahe ko",
        "pronunciation": "pah-kee-TAH-go moo-NAH ang bah-GAH-he koh",
        "sourceText": "Please hold my luggage",
        "audioKey": "tagalog-hotel-hostel-7",
        "accessTier": "starter",
        "context": "Use this if you need the desk to hold your bags",
        "usageNote": "Use this if you need the desk to hold your bags",
        "intentFamilyId": "tagalog-hotel-hostel-7",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🧳"
      }
    ]
  },
  {
    "id": "directions",
    "name": "Directions",
    "emoji": "🗺️",
    "description": "Find your way around town",
    "tip": "Save your hotel name and one landmark in your phone so you can ask for help even if maps fail.",
    "intentFamilies": [
      {
        "id": "tagalog-directions-1",
        "scenarioId": "directions",
        "title": "Excuse me, how do I get to this place?",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-directions-1",
        "phraseIds": [
          "tagalog-directions-1"
        ]
      },
      {
        "id": "tagalog-directions-2",
        "scenarioId": "directions",
        "title": "Is it near here?",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-directions-2",
        "phraseIds": [
          "tagalog-directions-2"
        ]
      },
      {
        "id": "tagalog-directions-3",
        "scenarioId": "directions",
        "title": "How long if I walk?",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-directions-3",
        "phraseIds": [
          "tagalog-directions-3"
        ]
      },
      {
        "id": "tagalog-directions-4",
        "scenarioId": "directions",
        "title": "Where do I turn left",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-directions-4",
        "phraseIds": [
          "tagalog-directions-4"
        ]
      },
      {
        "id": "tagalog-directions-5",
        "scenarioId": "directions",
        "title": "Turn right?",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-directions-5",
        "phraseIds": [
          "tagalog-directions-5"
        ]
      },
      {
        "id": "tagalog-directions-6",
        "scenarioId": "directions",
        "title": "Go straight",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-directions-6",
        "phraseIds": [
          "tagalog-directions-6"
        ]
      },
      {
        "id": "tagalog-directions-7",
        "scenarioId": "directions",
        "title": "Thanks I understand now",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-directions-7",
        "phraseIds": [
          "tagalog-directions-7"
        ]
      }
    ],
    "phrases": [
      {
        "id": "tagalog-directions-1",
        "scenarioId": "directions",
        "targetText": "Paumanhin, paano po pumunta sa lugar na ito",
        "canonicalTargetText": "Paumanhin, paano po pumunta sa lugar na ito",
        "pronunciation": "pah-oo-MAN-hin pah-AH-noh poh poo-MOON-tah sah loo-GAR nah ee-TOH",
        "sourceText": "Excuse me, how do I get to this place?",
        "audioKey": "tagalog-directions-1",
        "accessTier": "starter",
        "context": "Use this while showing a pinned place on your phone instead of naming a specific landmark",
        "usageNote": "Use this while showing a pinned place on your phone instead of naming a specific landmark",
        "intentFamilyId": "tagalog-directions-1",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🗺️"
      },
      {
        "id": "tagalog-directions-2",
        "scenarioId": "directions",
        "targetText": "Malapit lang ba ito",
        "canonicalTargetText": "Malapit lang ba ito",
        "pronunciation": "mah-LAH-pit lahng bah ee-TOH",
        "sourceText": "Is it near here?",
        "audioKey": "tagalog-directions-2",
        "accessTier": "starter",
        "context": "Ask this when deciding whether to walk or ride",
        "usageNote": "Ask this when deciding whether to walk or ride",
        "intentFamilyId": "tagalog-directions-2",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "📍"
      },
      {
        "id": "tagalog-directions-3",
        "scenarioId": "directions",
        "targetText": "Gaano katagal kung maglalakad ako",
        "canonicalTargetText": "Gaano katagal kung maglalakad ako",
        "pronunciation": "gah-AH-noh kah-tah-GAL koong mag-lah-LAH-kad ah-KOH",
        "sourceText": "How long if I walk?",
        "audioKey": "tagalog-directions-3",
        "accessTier": "starter",
        "context": "Use this to check whether walking is realistic",
        "usageNote": "Use this to check whether walking is realistic",
        "intentFamilyId": "tagalog-directions-3",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🚶"
      },
      {
        "id": "tagalog-directions-4",
        "scenarioId": "directions",
        "targetText": "Saan ako liliko pakaliwa",
        "canonicalTargetText": "Saan ako liliko pakaliwa",
        "pronunciation": "sah-AHN ah-KOH lee-LEE-koh pah-kah-LEE-wah",
        "sourceText": "Where do I turn left",
        "audioKey": "tagalog-directions-4",
        "accessTier": "starter",
        "context": "Ask this when someone is giving step by step directions",
        "usageNote": "Ask this when someone is giving step by step directions",
        "intentFamilyId": "tagalog-directions-4",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "⬅️"
      },
      {
        "id": "tagalog-directions-5",
        "scenarioId": "directions",
        "targetText": "Liliko sa kanan tama",
        "canonicalTargetText": "Liliko sa kanan tama",
        "pronunciation": "lee-LEE-koh sah kah-NAN tah-MAH",
        "sourceText": "Turn right?",
        "audioKey": "tagalog-directions-5",
        "accessTier": "starter",
        "context": "Use this to confirm the next turn",
        "usageNote": "Use this to confirm the next turn",
        "intentFamilyId": "tagalog-directions-5",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "➡️"
      },
      {
        "id": "tagalog-directions-6",
        "scenarioId": "directions",
        "targetText": "Dere-derecho lang",
        "canonicalTargetText": "Dere-derecho lang",
        "pronunciation": "deh-reh-DRET-soh lahng",
        "sourceText": "Go straight",
        "audioKey": "tagalog-directions-6",
        "accessTier": "starter",
        "context": "Use this to confirm you should keep moving forward",
        "usageNote": "Use this to confirm you should keep moving forward",
        "intentFamilyId": "tagalog-directions-6",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "⬆️"
      },
      {
        "id": "tagalog-directions-7",
        "scenarioId": "directions",
        "targetText": "Salamat naiintindihan ko na",
        "canonicalTargetText": "Salamat naiintindihan ko na",
        "pronunciation": "sah-LAH-mat nah-ee-in-tin-DEE-han koh nah",
        "sourceText": "Thanks I understand now",
        "audioKey": "tagalog-directions-7",
        "accessTier": "starter",
        "context": "Use this to politely end the directions exchange",
        "usageNote": "Use this to politely end the directions exchange",
        "intentFamilyId": "tagalog-directions-7",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🙏"
      }
    ]
  },
  {
    "id": "simple-problems",
    "name": "Simple Problems",
    "emoji": "⚠️",
    "description": "Handle common travel hiccups",
    "tip": "If something goes wrong stay calm and show booking screens photos or screenshots to speed up help.",
    "intentFamilies": [
      {
        "id": "tagalog-simple-problems-1",
        "scenarioId": "simple-problems",
        "title": "I'm lost",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-simple-problems-1",
        "phraseIds": [
          "tagalog-simple-problems-1"
        ]
      },
      {
        "id": "tagalog-simple-problems-2",
        "scenarioId": "simple-problems",
        "title": "I don't understand",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-simple-problems-2",
        "phraseIds": [
          "tagalog-simple-problems-2"
        ]
      },
      {
        "id": "tagalog-simple-problems-3",
        "scenarioId": "simple-problems",
        "title": "Can you speak a little slower?",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-simple-problems-3",
        "phraseIds": [
          "tagalog-simple-problems-3"
        ]
      },
      {
        "id": "tagalog-simple-problems-4",
        "scenarioId": "simple-problems",
        "title": "I left something behind",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-simple-problems-4",
        "phraseIds": [
          "tagalog-simple-problems-4"
        ]
      },
      {
        "id": "tagalog-simple-problems-5",
        "scenarioId": "simple-problems",
        "title": "The Wi-Fi isn't working",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-simple-problems-5",
        "phraseIds": [
          "tagalog-simple-problems-5"
        ]
      },
      {
        "id": "tagalog-simple-problems-6",
        "scenarioId": "simple-problems",
        "title": "I need a doctor",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-simple-problems-6",
        "phraseIds": [
          "tagalog-simple-problems-6"
        ]
      },
      {
        "id": "tagalog-simple-problems-7",
        "scenarioId": "simple-problems",
        "title": "Could you call them for me?",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-simple-problems-7",
        "phraseIds": [
          "tagalog-simple-problems-7"
        ]
      }
    ],
    "phrases": [
      {
        "id": "tagalog-simple-problems-1",
        "scenarioId": "simple-problems",
        "targetText": "Nawawala ako",
        "canonicalTargetText": "Nawawala ako",
        "pronunciation": "nah-wah-WAH-lah ah-KOH",
        "sourceText": "I'm lost",
        "audioKey": "tagalog-simple-problems-1",
        "accessTier": "starter",
        "context": "Use this when you need immediate help finding your way",
        "usageNote": "Use this when you need immediate help finding your way",
        "intentFamilyId": "tagalog-simple-problems-1",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "😵"
      },
      {
        "id": "tagalog-simple-problems-2",
        "scenarioId": "simple-problems",
        "targetText": "Hindi ko maintindihan",
        "canonicalTargetText": "Hindi ko maintindihan",
        "pronunciation": "hin-DEE koh ma-in-tin-DEE-han",
        "sourceText": "I don't understand",
        "audioKey": "tagalog-simple-problems-2",
        "accessTier": "starter",
        "context": "Say this when someone is speaking too quickly",
        "usageNote": "Say this when someone is speaking too quickly",
        "intentFamilyId": "tagalog-simple-problems-2",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🤔"
      },
      {
        "id": "tagalog-simple-problems-3",
        "scenarioId": "simple-problems",
        "targetText": "Puwede bang magsalita nang mas mabagal",
        "canonicalTargetText": "Puwede bang magsalita nang mas mabagal",
        "pronunciation": "poo-WEH-deh bahng mag-sah-LEE-tah nang mahs mah-BAH-gal",
        "sourceText": "Can you speak a little slower?",
        "audioKey": "tagalog-simple-problems-3",
        "accessTier": "starter",
        "context": "Use this when you need the other person to slow down",
        "usageNote": "Use this when you need the other person to slow down",
        "intentFamilyId": "tagalog-simple-problems-3",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🐢"
      },
      {
        "id": "tagalog-simple-problems-4",
        "scenarioId": "simple-problems",
        "targetText": "May naiwan ako",
        "canonicalTargetText": "May naiwan ako",
        "pronunciation": "may nah-ee-WAN ah-KOH",
        "sourceText": "I left something behind",
        "audioKey": "tagalog-simple-problems-4",
        "accessTier": "starter",
        "context": "Say this if you forgot an item in a car room or cafe",
        "usageNote": "Say this if you forgot an item in a car room or cafe",
        "intentFamilyId": "tagalog-simple-problems-4",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🎒"
      },
      {
        "id": "tagalog-simple-problems-5",
        "scenarioId": "simple-problems",
        "targetText": "Hindi gumagana ang Wi-Fi",
        "canonicalTargetText": "Hindi gumagana ang Wi-Fi",
        "pronunciation": "hin-DEE goo-ma-GAH-na ang WAI-fai",
        "sourceText": "The Wi-Fi isn't working",
        "audioKey": "tagalog-simple-problems-5",
        "accessTier": "starter",
        "context": "Use this at hotels or cafes when you cannot connect",
        "usageNote": "Use this at hotels or cafes when you cannot connect",
        "intentFamilyId": "tagalog-simple-problems-5",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "📶"
      },
      {
        "id": "tagalog-simple-problems-6",
        "scenarioId": "simple-problems",
        "targetText": "Kailangan ko ng doktor",
        "canonicalTargetText": "Kailangan ko ng doktor",
        "pronunciation": "kah-ee-LAH-ngan koh nang dok-TOR",
        "sourceText": "I need a doctor",
        "audioKey": "tagalog-simple-problems-6",
        "accessTier": "starter",
        "context": "Use this if you feel sick and need medical help",
        "usageNote": "Use this if you feel sick and need medical help",
        "intentFamilyId": "tagalog-simple-problems-6",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🩺"
      },
      {
        "id": "tagalog-simple-problems-7",
        "scenarioId": "simple-problems",
        "targetText": "Puwede po ba ninyong tawagan sila para sa akin",
        "canonicalTargetText": "Puwede po ba ninyong tawagan sila para sa akin",
        "pronunciation": "poo-WEH-deh poh bah nin-YOHNG tah-WAH-gan see-LAH pah-rah sah ah-KIN",
        "sourceText": "Could you call them for me?",
        "audioKey": "tagalog-simple-problems-7",
        "accessTier": "starter",
        "context": "Use this when you need a hotel desk driver or staff member to call for you",
        "usageNote": "Use this when you need a hotel desk driver or staff member to call for you",
        "intentFamilyId": "tagalog-simple-problems-7",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "📞"
      }
    ]
  },
  {
    "id": "small-talk",
    "name": "Small Talk",
    "emoji": "💬",
    "description": "Make light conversation",
    "tip": "Short friendly chat often starts with where you are from whether it is your first visit and what food you like.",
    "intentFamilies": [
      {
        "id": "tagalog-small-talk-1",
        "scenarioId": "small-talk",
        "title": "I'm from the United States",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-small-talk-1",
        "phraseIds": [
          "tagalog-small-talk-1"
        ]
      },
      {
        "id": "tagalog-small-talk-2",
        "scenarioId": "small-talk",
        "title": "I'm from England",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-small-talk-2",
        "phraseIds": [
          "tagalog-small-talk-2"
        ]
      },
      {
        "id": "tagalog-small-talk-3",
        "scenarioId": "small-talk",
        "title": "This is my first time",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-small-talk-3",
        "phraseIds": [
          "tagalog-small-talk-3"
        ]
      },
      {
        "id": "tagalog-small-talk-4",
        "scenarioId": "small-talk",
        "title": "I like the Philippines",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-small-talk-4",
        "phraseIds": [
          "tagalog-small-talk-4"
        ]
      },
      {
        "id": "tagalog-small-talk-5",
        "scenarioId": "small-talk",
        "title": "The food is so good",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-small-talk-5",
        "phraseIds": [
          "tagalog-small-talk-5"
        ]
      },
      {
        "id": "tagalog-small-talk-6",
        "scenarioId": "small-talk",
        "title": "The weather is so hot",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-small-talk-6",
        "phraseIds": [
          "tagalog-small-talk-6"
        ]
      },
      {
        "id": "tagalog-small-talk-7",
        "scenarioId": "small-talk",
        "title": "How are you",
        "accessTier": "starter",
        "primaryPhraseId": "tagalog-small-talk-7",
        "phraseIds": [
          "tagalog-small-talk-7"
        ]
      }
    ],
    "phrases": [
      {
        "id": "tagalog-small-talk-1",
        "scenarioId": "small-talk",
        "targetText": "Taga Estados Unidos ako",
        "canonicalTargetText": "Taga Estados Unidos ako",
        "pronunciation": "tah-gah ehs-TAH-dos oo-NEE-dos ah-KOH",
        "sourceText": "I'm from the United States",
        "audioKey": "tagalog-small-talk-1",
        "accessTier": "starter",
        "context": "Use this when someone asks where you are from",
        "usageNote": "Use this when someone asks where you are from",
        "intentFamilyId": "tagalog-small-talk-1",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🇺🇸"
      },
      {
        "id": "tagalog-small-talk-2",
        "scenarioId": "small-talk",
        "targetText": "Taga Inglatera ako",
        "canonicalTargetText": "Taga Inglatera ako",
        "pronunciation": "tah-gah ing-glah-TEH-rah ah-KOH",
        "sourceText": "I'm from England",
        "audioKey": "tagalog-small-talk-2",
        "accessTier": "starter",
        "context": "Use this as a simple answer when introducing yourself",
        "usageNote": "Use this as a simple answer when introducing yourself",
        "intentFamilyId": "tagalog-small-talk-2",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "🇬🇧"
      },
      {
        "id": "tagalog-small-talk-3",
        "scenarioId": "small-talk",
        "targetText": "Unang beses ko ito",
        "canonicalTargetText": "Unang beses ko ito",
        "pronunciation": "OO-nang BEH-ses koh ee-TOH",
        "sourceText": "This is my first time",
        "audioKey": "tagalog-small-talk-3",
        "accessTier": "starter",
        "context": "Say this when talking about your first visit",
        "usageNote": "Say this when talking about your first visit",
        "intentFamilyId": "tagalog-small-talk-3",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "✨"
      },
      {
        "id": "tagalog-small-talk-4",
        "scenarioId": "small-talk",
        "targetText": "Gusto ko ang Pilipinas",
        "canonicalTargetText": "Gusto ko ang Pilipinas",
        "pronunciation": "GOOS-toh koh ang pee-lee-PEE-nas",
        "sourceText": "I like the Philippines",
        "audioKey": "tagalog-small-talk-4",
        "accessTier": "starter",
        "context": "Use this as an easy positive comment in conversation",
        "usageNote": "Use this as an easy positive comment in conversation",
        "intentFamilyId": "tagalog-small-talk-4",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "❤️"
      },
      {
        "id": "tagalog-small-talk-5",
        "scenarioId": "small-talk",
        "targetText": "Ang sarap ng pagkain",
        "canonicalTargetText": "Ang sarap ng pagkain",
        "pronunciation": "ang sah-RAP nang pag-kah-IN",
        "sourceText": "The food is so good",
        "audioKey": "tagalog-small-talk-5",
        "accessTier": "starter",
        "context": "Use this to compliment a meal or recommendation",
        "usageNote": "Use this to compliment a meal or recommendation",
        "intentFamilyId": "tagalog-small-talk-5",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "😋"
      },
      {
        "id": "tagalog-small-talk-6",
        "scenarioId": "small-talk",
        "targetText": "Napakainit ng panahon",
        "canonicalTargetText": "Napakainit ng panahon",
        "pronunciation": "nah-pah-kah-EE-nit nang pah-nah-HON",
        "sourceText": "The weather is so hot",
        "audioKey": "tagalog-small-talk-6",
        "accessTier": "starter",
        "context": "Use this as easy weather small talk on a hot day",
        "usageNote": "Use this as easy weather small talk on a hot day",
        "intentFamilyId": "tagalog-small-talk-6",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "☀️"
      },
      {
        "id": "tagalog-small-talk-7",
        "scenarioId": "small-talk",
        "targetText": "Kumusta ka",
        "canonicalTargetText": "Kumusta ka",
        "pronunciation": "koo-MOOS-tah kah",
        "sourceText": "How are you",
        "audioKey": "tagalog-small-talk-7",
        "accessTier": "starter",
        "context": "Use this with friendly staff or locals after a greeting",
        "usageNote": "Use this with friendly staff or locals after a greeting",
        "intentFamilyId": "tagalog-small-talk-7",
        "variantRole": "say-first",
        "variantLabel": "Say this first",
        "audioStatus": "ready",
        "emoji": "😊"
      }
    ]
  }
];

const intentFamilies = scenarios.flatMap((scenario) => scenario.intentFamilies);
const phrases = scenarios.flatMap((scenario) => scenario.phrases);

export const tagalogPack: AppPack = {
  metadata: {
    appId: "tagalog-travel-phrases",
    packId: "tagalog",
    displayName: "SpeakLocal Philippines",
    country: "Philippines",
    language: "Tagalog",
    languageCode: "tl",
    schemaVersion: 2,
  },
  scenarios,
  intentFamilies,
  phrases,
  scenarioMap: Object.fromEntries(
    scenarios.map((scenario) => [scenario.id, scenario]),
  ) as Record<string, AppScenario>,
  intentFamilyMap: Object.fromEntries(
    intentFamilies.map((family) => [family.id, family]),
  ) as Record<string, AppIntentFamily>,
  phraseMap: Object.fromEntries(
    phrases.map((phrase) => [phrase.id, phrase]),
  ) as Record<string, AppPhrase>,
};
