import { AppPremiumCategory, AppPremiumConfig } from '../contracts';

const sharedPremiumCategories: AppPremiumCategory[] = [
  {
    id: 'polite-basics',
    title: 'Greetings and basics',
    emoji: '👋',
    description: 'Short polite phrases for counters, greetings, and everyday travel moments.',
    scenarioId: 'polite-basics',
    access: 'starter',
    availability: 'live',
    starterPhraseTarget: 15,
    totalPhraseTarget: 40,
    highlights: ['hello', 'thank you', 'yes and no', 'excuse me'],
  },
  {
    id: 'coffee-shop',
    title: 'Cafe and coffee',
    emoji: '☕',
    description: 'Order drinks quickly, adjust sweetness, and pay without friction.',
    scenarioId: 'coffee-shop',
    access: 'starter',
    availability: 'live',
    starterPhraseTarget: 15,
    totalPhraseTarget: 35,
    highlights: ['less ice', 'milk choices', 'to go', 'pay here'],
  },
  {
    id: 'street-food',
    title: 'Food and restaurants',
    emoji: '🍜',
    description: 'Handle menu questions, spice levels, takeout, and table basics.',
    scenarioId: 'street-food',
    access: 'starter',
    availability: 'live',
    starterPhraseTarget: 15,
    totalPhraseTarget: 50,
    highlights: ['not spicy', 'water', 'utensils', 'pack it up'],
  },
  {
    id: 'grab-taxi',
    title: 'Taxi and rides',
    emoji: '🚕',
    description: 'Show your destination, guide the route, and settle the ride smoothly.',
    scenarioId: 'grab-taxi',
    access: 'starter',
    availability: 'live',
    starterPhraseTarget: 15,
    totalPhraseTarget: 45,
    highlights: ['drop off here', 'wait for me', 'cash', 'aircon'],
  },
  {
    id: 'asking-price',
    title: 'Shopping and prices',
    emoji: '🛍️',
    description: 'Ask prices, compare options, and check out with more confidence.',
    scenarioId: 'asking-price',
    access: 'starter',
    availability: 'live',
    starterPhraseTarget: 15,
    totalPhraseTarget: 40,
    highlights: ['how much', 'compare items', 'too expensive', 'final price'],
  },
  {
    id: 'convenience-store',
    title: 'Quick essentials',
    emoji: '🏪',
    description: 'Pick up water, tissues, sunscreen, and small travel necessities.',
    scenarioId: 'convenience-store',
    access: 'starter',
    availability: 'live',
    starterPhraseTarget: 15,
    totalPhraseTarget: 35,
    highlights: ['water', 'bag', 'tissues', 'sunscreen'],
  },
  {
    id: 'hotel-hostel',
    title: 'Hotel stay',
    emoji: '🏨',
    description: 'Handle check-in, room issues, and front-desk requests with less stress.',
    scenarioId: 'hotel-hostel',
    access: 'starter',
    availability: 'live',
    starterPhraseTarget: 15,
    totalPhraseTarget: 45,
    highlights: ['check-in', 'key card', 'extra towel', 'late checkout'],
  },
  {
    id: 'directions',
    title: 'Directions',
    emoji: '🗺️',
    description: 'Ask where things are, confirm turns, and get back on track quickly.',
    scenarioId: 'directions',
    access: 'starter',
    availability: 'live',
    starterPhraseTarget: 15,
    totalPhraseTarget: 35,
    highlights: ['left or right', 'nearby', 'how far', 'landmark help'],
  },
  {
    id: 'simple-problems',
    title: 'Misunderstandings',
    emoji: '🧭',
    description: 'Recover when something goes wrong or you need clarification.',
    scenarioId: 'simple-problems',
    access: 'starter',
    availability: 'live',
    starterPhraseTarget: 15,
    totalPhraseTarget: 35,
    highlights: ['repeat slowly', 'wrong order', 'can you help', 'I am lost'],
  },
  {
    id: 'small-talk',
    title: 'Friendly small talk',
    emoji: '💬',
    description: 'Make light conversation without turning the app into language school.',
    scenarioId: 'small-talk',
    access: 'starter',
    availability: 'live',
    starterPhraseTarget: 15,
    totalPhraseTarget: 30,
    highlights: ['where are you from', 'first trip', 'food you like', 'nice to meet you'],
  },
  {
    id: 'airport-arrival',
    title: 'Airport and arrival',
    emoji: '🛬',
    description: 'Land, collect bags, and reach the city with fewer awkward moments.',
    access: 'premium-only',
    availability: 'planned',
    starterPhraseTarget: 0,
    totalPhraseTarget: 45,
    highlights: ['immigration', 'pickup point', 'bags', 'transfer desk'],
  },
  {
    id: 'money-exchange',
    title: 'Money and exchange',
    emoji: '💱',
    description: 'Handle exchange counters, ATMs, and cash questions on the road.',
    access: 'premium-only',
    availability: 'planned',
    starterPhraseTarget: 0,
    totalPhraseTarget: 35,
    highlights: ['exchange rate', 'ATM help', 'small bills', 'receipt'],
  },
  {
    id: 'checkout-payment',
    title: 'Paying and checkout',
    emoji: '💳',
    description: 'Pay clearly, split the bill, and confirm the total before you leave.',
    access: 'premium-only',
    availability: 'planned',
    starterPhraseTarget: 0,
    totalPhraseTarget: 30,
    highlights: ['card or cash', 'bill please', 'split payment', 'receipt'],
  },
  {
    id: 'asking-for-help',
    title: 'Asking for help',
    emoji: '🆘',
    description: 'Get practical help when you need a hand, a person, or a quick fix.',
    access: 'premium-only',
    availability: 'planned',
    starterPhraseTarget: 0,
    totalPhraseTarget: 45,
    highlights: ['can you help', 'I need someone', 'call the hotel', 'I do not understand'],
  },
  {
    id: 'medical-pharmacy',
    title: 'Medical and pharmacy',
    emoji: '💊',
    description: 'Explain basic symptoms and ask for the most common travel remedies.',
    access: 'premium-only',
    availability: 'planned',
    starterPhraseTarget: 0,
    totalPhraseTarget: 40,
    highlights: ['headache', 'stomach issue', 'allergy', 'where is the pharmacy'],
  },
  {
    id: 'restroom-facilities',
    title: 'Restrooms and facilities',
    emoji: '🚻',
    description: 'Find restrooms, water, and the small facilities every traveler needs.',
    access: 'premium-only',
    availability: 'planned',
    starterPhraseTarget: 0,
    totalPhraseTarget: 25,
    highlights: ['restroom', 'soap', 'water refill', 'changing room'],
  },
  {
    id: 'phone-connectivity',
    title: 'Phone and SIM help',
    emoji: '📱',
    description: 'Ask about eSIM, SIM cards, top-ups, and getting reconnected quickly.',
    access: 'premium-only',
    availability: 'planned',
    starterPhraseTarget: 0,
    totalPhraseTarget: 30,
    highlights: ['SIM card', 'data top-up', 'wifi password', 'no signal'],
  },
  {
    id: 'local-etiquette',
    title: 'Local etiquette',
    emoji: '🙏',
    description: 'Handle respect, courtesy, and common cultural moments more gracefully.',
    access: 'premium-only',
    availability: 'planned',
    starterPhraseTarget: 0,
    totalPhraseTarget: 35,
    highlights: ['formal thanks', 'respectful address', 'temple manners', 'house rules'],
  },
  {
    id: 'time-scheduling',
    title: 'Time and scheduling',
    emoji: '🕒',
    description: 'Confirm times, meeting points, and the basics of making a plan.',
    access: 'premium-only',
    availability: 'planned',
    starterPhraseTarget: 0,
    totalPhraseTarget: 30,
    highlights: ['what time', 'tomorrow morning', 'meet here', 'opening hours'],
  },
  {
    id: 'emergencies',
    title: 'Emergencies',
    emoji: '🚨',
    description: 'Keep a calmer script ready for urgent travel situations.',
    access: 'premium-only',
    availability: 'planned',
    starterPhraseTarget: 0,
    totalPhraseTarget: 45,
    highlights: ['call police', 'need a doctor', 'lost passport', 'unsafe situation'],
  },
];

type CreateSharedPremiumConfigOptions = {
  appName: string;
  language: string;
  country: string;
};

export function createSharedPremiumConfig({
  appName,
  language,
  country,
}: CreateSharedPremiumConfigOptions): AppPremiumConfig {
  return {
    priceLabel: '$4.99',
    unlockModelLabel: 'One-time unlock',
    freePhraseTarget: 150,
    totalPhraseTarget: 750,
    categoryTarget: sharedPremiumCategories.length,
    teaserBadge: 'Full library preview',
    teaserTitle: `See the full ${language} traveler library`,
    teaserBody: `Start with a useful offline starter pack now, then preview how the fuller ${language} phrasebook is planned to grow into more trip-ready situations.`,
    teaserButtonLabel: 'See full library preview',
    statusLockedLabel: 'Full library preview',
    statusUnlockedLabel: 'Full library unlocked',
    screenTitle: `${appName} full library`,
    screenBody: `This preview maps the planned one-time unlock for travelers going to ${country}: a practical starter pack today, with a deeper offline phrasebook as more categories are authored.`,
    unlockButtonLabel: 'Unlock for $4.99',
    restoreButtonLabel: 'Restore purchase',
    storeUnavailableTitle: 'Full library preview only',
    storePlaceholderBody:
      'This build previews the planned one-time unlock structure. Real purchase and restore still need the App Store connection before release.',
    restoredAlertTitle: 'Restore not available yet',
    restoredAlertBody: 'Restore will become available after the real App Store purchase flow is wired.',
    previewEnableLabel: 'Preview unlocked state',
    previewDisableLabel: 'Reset preview unlock',
    benefits: [
      'A useful starter pack stays available without subscriptions.',
      'The full phrasebook is planned to expand into 750 total phrases across about 20 traveler categories.',
      'More trip-specific depth is planned for airport, hotel, medical, emergencies, payments, and SIM help.',
      'The target unlock model is one purchase only, with no account dependency.',
    ],
    categories: sharedPremiumCategories,
    featuredCategoryIds: ['polite-basics', 'grab-taxi', 'street-food', 'hotel-hostel'],
    liveSectionTitle: 'Starter categories live now',
    liveSectionBody:
      'These categories already exist in the app today and keep free users productive while the bigger phrasebook is authored.',
    plannedSectionTitle: 'Full library preview',
    plannedSectionBody:
      'These are the next categories planned for the fuller traveler library once content expansion and the one-time unlock are ready.',
    scenarioPreviewTitle: 'Category expansion preview',
    scenarioPreviewBody:
      'This starter category is planned to grow into a deeper traveler pack with more phrases for the same situation.',
    includedBadgeLabel: 'Starter included',
    premiumOnlyBadgeLabel: 'Premium preview',
    liveNowBadgeLabel: 'Live now',
    plannedBadgeLabel: 'Planned',
    liveNowStatLabel: 'Live now',
    starterStatLabel: 'Free target',
    fullLibraryStatLabel: 'Full target',
    manageTitle: 'Premium unlock',
    manageBody: `The plan is one purchase for the full ${language} phrasebook, while keeping the app offline-friendly and simple to use.`,
  };
}
