import { AppPremiumConfig } from '../contracts';

export const vietPremiumConfig: AppPremiumConfig = {
  priceLabel: '$4.99',
  unlockModelLabel: 'One-time purchase',
  freePhraseTarget: 150,
  totalPhraseTarget: 900,
  categoryTarget: 18,
  teaserBadge: 'Full Trip Pack',
  teaserTitle: 'Free handles the first step. Full Trip Pack helps with the follow-up.',
  teaserBody: 'Keep the same travel situations and open deeper follow-up, repair, and recovery help inside them.',
  teaserButtonLabel: "See what's included",
  statusLockedLabel: 'Trip Pack locked',
  statusUnlockedLabel: 'Trip Pack unlocked',
  screenTitle: 'When the first phrase is not enough',
  screenBody:
    'Free covers 150 starter phrase groups across all 18 travel situations. Full Trip Pack adds 750 more follow-up and recovery groups in those same situations, bringing the Viet library to 900 live phrase groups.',
  unlockButtonLabel: 'Unlock for $4.99',
  restoreButtonLabel: 'Restore Purchase',
  storeUnavailableTitle: 'Not available right now',
  storePlaceholderBody:
    'Full Trip Pack uses a one-time App Store purchase in supported iPhone builds. Buy and restore stay unavailable until this build can reach the App Store item.',
  restoredAlertTitle: 'Restored',
  restoredAlertBody: 'Full Trip Pack is unlocked again on this iPhone.',
  previewEnableLabel: 'Enable preview unlock',
  previewDisableLabel: 'Clear preview unlock',
  benefits: [
    'Buy once. No subscription.',
    'Free already covers 150 starter phrase groups across all 18 travel situations.',
    'Full Trip Pack adds 750 deeper follow-up and recovery groups in those same situations.',
    'High-stress help goes deeper in arrival, transport, money, food, pharmacy, emergencies, SIM/internet, and misunderstanding repair.',
    'All 919 current Viet lines include audio.',
  ],
  categories: [
    {
      id: 'polite-basics',
      title: 'Polite Basics',
      emoji: '\uD83D\uDE4F',
      description: 'The short polite phrases you use all day.',
      scenarioId: 'polite-basics',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 8,
      totalPhraseTarget: 20,
      highlights: ['hello', 'thank you', 'excuse me', 'goodbye'],
    },
    {
      id: 'understanding-repair',
      title: 'Repeat & Clarify',
      emoji: '\uD83E\uDDED',
      description: 'Repeat, slow down, or move the conversation to writing.',
      scenarioId: 'understanding-repair',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 8,
      totalPhraseTarget: 55,
      highlights: ['I do not understand', 'speak slower', 'say it again', 'write it down'],
    },
    {
      id: 'transport',
      title: 'Transport',
      emoji: '\uD83D\uDE95',
      description: 'Handle rides, buses, and stations with less confusion.',
      scenarioId: 'transport',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 10,
      totalPhraseTarget: 93,
      highlights: ['take me here', 'stop here', 'cash', 'right platform'],
    },
    {
      id: 'hotel-accommodation',
      title: 'Hotel & Room',
      emoji: '\uD83C\uDFE8',
      description: 'Handle check-in, room issues, and front desk fixes.',
      scenarioId: 'hotel-accommodation',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 9,
      totalPhraseTarget: 79,
      highlights: ['check in', 'check out', 'air conditioner', 'key card'],
    },
    {
      id: 'food-drink',
      title: 'Food & Drink',
      emoji: '\uD83C\uDF5C',
      description: 'Order, adjust the meal, and fix the order when needed.',
      scenarioId: 'food-drink',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 18,
      totalPhraseTarget: 92,
      highlights: ['coffee', 'not spicy', 'water', 'wrong order'],
    },
    {
      id: 'money-numbers-prices',
      title: 'Prices & Payment',
      emoji: '\uD83D\uDCB5',
      description: 'Check prices and pay without getting lost in the numbers.',
      scenarioId: 'money-numbers-prices',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 9,
      totalPhraseTarget: 62,
      highlights: ['how much', 'per kilo', 'final price', 'small bills'],
    },
    {
      id: 'directions-navigation',
      title: 'Directions',
      emoji: '\uD83D\uDDFA\uFE0F',
      description: 'Get where you need to go one turn at a time.',
      scenarioId: 'directions-navigation',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 8,
      totalPhraseTarget: 52,
      highlights: ['near here', 'turn left', 'go straight', 'which exit'],
    },
    {
      id: 'airport-border-arrival',
      title: 'Airport & Arrival',
      emoji: '\uD83D\uDEE4',
      description: 'Get through arrival and into the city.',
      scenarioId: 'airport-border-arrival',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 8,
      totalPhraseTarget: 55,
      highlights: ['immigration', 'baggage claim', 'SIM', 'pickup area'],
    },
    {
      id: 'health-pharmacy',
      title: 'Health & Pharmacy',
      emoji: '\uD83D\uDC8A',
      description: 'Cover common travel symptoms and pharmacy needs.',
      scenarioId: 'health-pharmacy',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 8,
      totalPhraseTarget: 65,
      highlights: ['doctor', 'pharmacy', 'headache', 'stomach hurts'],
    },
    {
      id: 'problems-help',
      title: 'Get Help',
      emoji: '\uD83C\uDD98',
      description: 'Get practical help when something goes wrong.',
      scenarioId: 'problems-help',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 6,
      totalPhraseTarget: 41,
      highlights: ['I am lost', 'left something', 'help me', 'call the hotel'],
    },
    {
      id: 'time-dates-booking',
      title: 'Time & Bookings',
      emoji: '\uD83D\uDD52',
      description: 'Confirm times, dates, and booking details.',
      scenarioId: 'time-dates-booking',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 7,
      totalPhraseTarget: 59,
      highlights: ['what time', 'today', 'tomorrow morning', 'booking'],
    },
    {
      id: 'shopping',
      title: 'Shopping',
      emoji: '\uD83D\uDED2',
      description: 'Compare size, color, fit, and checkout.',
      scenarioId: 'shopping',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 7,
      totalPhraseTarget: 37,
      highlights: ['this size', 'another color', 'try it on', 'where do I pay'],
    },
    {
      id: 'phone-internet-power',
      title: 'Phone & Internet',
      emoji: '\uD83D\uDCF1',
      description: 'Get your phone, data, or battery working again.',
      scenarioId: 'phone-internet-power',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 8,
      totalPhraseTarget: 47,
      highlights: ['Wi-Fi password', 'SIM', 'charger', 'charge phone'],
    },
    {
      id: 'bathroom-personal-needs',
      title: 'Bathroom & Basics',
      emoji: '\uD83D\uDEBB',
      description: 'Handle the small needs that still matter on the road.',
      scenarioId: 'bathroom-personal-needs',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 6,
      totalPhraseTarget: 14,
      highlights: ['bathroom', 'toilet paper', 'soap', 'water'],
    },
    {
      id: 'emergency-safety',
      title: 'Emergency & Safety',
      emoji: '\uD83D\uDEA8',
      description: 'Keep emergency phrases short and easy to reach.',
      scenarioId: 'emergency-safety',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 9,
      totalPhraseTarget: 43,
      highlights: ['police', 'ambulance', 'passport', 'help'],
    },
    {
      id: 'social-small-talk',
      title: 'Small Talk',
      emoji: '\uD83D\uDCAC',
      description: 'Stay friendly without overthinking it.',
      scenarioId: 'social-small-talk',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 7,
      totalPhraseTarget: 17,
      highlights: ['where I am from', 'first time', 'food is good', 'recommend here'],
    },
    {
      id: 'sightseeing-activities',
      title: 'Sightseeing',
      emoji: '\uD83D\uDCF8',
      description: 'Use simple phrases for tickets, times, and meeting points.',
      scenarioId: 'sightseeing-activities',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 6,
      totalPhraseTarget: 28,
      highlights: ['ticket', 'start here', 'photos', 'meeting point'],
    },
    {
      id: 'local-services-everyday-tasks',
      title: 'Everyday Errands',
      emoji: '\uD83C\uDFEA',
      description: 'Handle the little errands that keep the trip moving.',
      scenarioId: 'local-services-everyday-tasks',
      access: 'starter',
      availability: 'live',
      starterPhraseTarget: 8,
      totalPhraseTarget: 41,
      highlights: ['water', 'bag', 'tissues', 'print this'],
    },
  ],
  featuredCategoryIds: [
    'airport-border-arrival',
    'transport',
    'money-numbers-prices',
    'food-drink',
    'health-pharmacy',
    'emergency-safety',
    'phone-internet-power',
    'understanding-repair',
  ],
  liveSectionTitle: 'Travel situations you can use now',
  liveSectionBody:
    'Free already covers every live situation. Full Trip Pack adds deeper follow-up phrases inside them.',
  plannedSectionTitle: 'More coming later',
  plannedSectionBody: 'These situations are planned next, but they are not part of the live app yet.',
  scenarioPreviewTitle: 'More in Full Trip Pack',
  scenarioPreviewBody:
    'Free covers the basics in this situation. Full Trip Pack adds the follow-up and repair phrases that usually come next.',
  includedBadgeLabel: 'Free',
  premiumOnlyBadgeLabel: 'Full Trip Pack',
  liveNowBadgeLabel: 'Open',
  plannedBadgeLabel: 'Coming later',
  liveNowStatLabel: 'Free',
  starterStatLabel: 'Free',
  fullLibraryStatLabel: 'Total',
  manageTitle: 'Full Trip Pack',
  manageBody:
    'Free covers 150 starter phrase groups across all 18 travel situations. Full Trip Pack adds 750 more in those same situations, bringing Viet to 900 live phrase groups.',
};
