import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { resolveScriptRoots } from './resolve-script-roots';

type DraftVariantRole = 'say-first' | 'more-polite' | 'clearer' | 'also-common';
type DraftWarningNoteType = 'formal' | 'bookish' | 'harder-to-say' | 'recognition-only';
type DraftAudioStatus = 'ready' | 'planned';

type DraftScenario = {
  order: number;
  id: string;
  name: string;
  emoji: string;
  description: string;
  tip: string;
};

type DraftPhrase = {
  phrase_id: string;
  scenario_id: string;
  family_id?: string;
  family_title?: string;
  family_summary?: string;
  related_family_id?: string;
  audio_key: string;
  english_text: string;
  target_text: string;
  canonical_target_text?: string;
  pronunciation: string;
  access_tier?: string;
  variant_role?: string;
  context: string;
  you_may_hear?: string;
  search_aliases?: string;
  warning_note_type?: string;
  audio_status?: string;
  emoji: string;
  notes?: string;
  status?: string;
};

type DraftPlan = {
  variant?: string;
  appId: string;
  displayName?: string;
  language: string;
  languageCode?: string;
  country: string;
  scenarioOrder: string[];
  quickPhraseIds: string[];
  scenarios: DraftScenario[];
  notes?: string;
};

type CliArgs = {
  variant?: string;
  output?: string;
};

type BuiltPhrase = {
  id: string;
  scenarioId: string;
  targetText: string;
  canonicalTargetText: string;
  pronunciation: string;
  sourceText: string;
  audioKey: string;
  accessTier: 'starter' | 'premium';
  context: string;
  usageNote: string;
  youMayHear?: string;
  searchAliases?: string[];
  intentFamilyId: string;
  variantRole: DraftVariantRole;
  variantLabel: string;
  warningNoteType?: DraftWarningNoteType;
  audioStatus: DraftAudioStatus;
  emoji: string;
};

const { appRoot: APP_ROOT, repoRoot: REPO_ROOT } = resolveScriptRoots(import.meta.url);
const SUPPORTED_SCHEMA_VERSION = 2;

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const variant = normalizeVariant(args.variant);

  if (!variant) {
    throw new Error('Missing required --variant argument.');
  }

  const draftDir = path.join(REPO_ROOT, 'content-draft', variant);
  const planPath = path.join(draftDir, 'scenario-plan.json');
  const phrasePath = path.join(draftDir, 'phrase-source.csv');
  const outputPath = args.output
    ? resolveOutputPath(args.output)
    : path.join(APP_ROOT, 'family', 'packs', `${variant}.generated.ts`);

  const plan = JSON.parse(await readFile(planPath, 'utf8')) as DraftPlan;
  const phrases = parseCsv(await readFile(phrasePath, 'utf8')) as DraftPhrase[];

  validateDraftPlan(plan, phrases, variant);

  const scenarios = [...plan.scenarios]
    .sort((left, right) => left.order - right.order)
    .map((scenario) => buildScenario(scenario, phrases.filter((phrase) => phrase.scenario_id === scenario.id)));

  const displayName = plan.displayName?.trim() || `${plan.language.trim()} Travel Phrasebook`;
  const languageCode = plan.languageCode?.trim();

  if (!languageCode) {
    throw new Error(`Draft plan for "${variant}" is missing languageCode.`);
  }

  const exportName = `${toIdentifier(variant)}Pack`;

  const output = `import { AppIntentFamily, AppPack, AppPhrase, AppScenario } from '../contracts';

// Generated by scripts/build-family-pack.ts. Do not edit manually.
const scenarios: AppScenario[] = ${JSON.stringify(scenarios, null, 2)};

const intentFamilies = scenarios.flatMap((scenario) => scenario.intentFamilies);
const phrases = scenarios.flatMap((scenario) => scenario.phrases);

export const ${exportName}: AppPack = {
  metadata: {
    appId: ${JSON.stringify(plan.appId)},
    packId: ${JSON.stringify(variant)},
    displayName: ${JSON.stringify(displayName)},
    country: ${JSON.stringify(plan.country)},
    language: ${JSON.stringify(plan.language)},
    languageCode: ${JSON.stringify(languageCode)},
    schemaVersion: ${SUPPORTED_SCHEMA_VERSION},
  },
  scenarios,
  intentFamilies,
  phrases,
  scenarioMap: Object.fromEntries(
    scenarios.map((scenario) => [scenario.id, scenario]),
  ) as Record<string, AppScenario>,
  intentFamilyMap: Object.fromEntries(
    intentFamilies.map((family) => [family.id, family]),
  ) as Record<string, AppIntentFamily>,
  phraseMap: Object.fromEntries(
    phrases.map((phrase) => [phrase.id, phrase]),
  ) as Record<string, AppPhrase>,
};
`;

  await writeFile(outputPath, output, 'utf8');

  console.log(
    `Built ${variant} pack with ${scenarios.length} scenarios, ${intentFamilyCount(scenarios)} intent families, and ${phraseCount(
      scenarios,
    )} phrases -> ${outputPath}`,
  );
}

function validateDraftPlan(plan: DraftPlan, phrases: DraftPhrase[], variant: string) {
  if (!plan.appId?.trim()) {
    throw new Error(`Draft plan for "${variant}" is missing appId.`);
  }

  if (!plan.language?.trim() || !plan.country?.trim()) {
    throw new Error(`Draft plan for "${variant}" is missing language or country metadata.`);
  }

  if (plan.variant && normalizeVariant(plan.variant) !== variant) {
    throw new Error(`Draft plan variant "${plan.variant}" does not match requested variant "${variant}".`);
  }

  if (!plan.scenarios.length) {
    throw new Error(`Draft plan for "${variant}" must define at least one scenario.`);
  }

  if (!plan.scenarioOrder.length) {
    throw new Error(`Draft plan for "${variant}" must define scenarioOrder.`);
  }

  const scenarioIds = new Set(plan.scenarios.map((scenario) => scenario.id));
  if (scenarioIds.size !== plan.scenarios.length) {
    throw new Error(`Draft plan for "${variant}" contains duplicate scenario IDs.`);
  }

  if (new Set(plan.scenarioOrder).size !== plan.scenarioOrder.length) {
    throw new Error(`Draft plan for "${variant}" contains duplicate scenarioOrder entries.`);
  }

  for (const scenarioId of plan.scenarioOrder) {
    if (!scenarioIds.has(scenarioId)) {
      throw new Error(`Draft plan for "${variant}" references unknown scenario "${scenarioId}" in scenarioOrder.`);
    }
  }

  if (!plan.quickPhraseIds.length) {
    throw new Error(`Draft plan for "${variant}" must define quickPhraseIds.`);
  }

  if (new Set(plan.quickPhraseIds).size !== plan.quickPhraseIds.length) {
    throw new Error(`Draft plan for "${variant}" contains duplicate quickPhraseIds.`);
  }

  if (!phrases.length) {
    throw new Error(`Draft phrases for "${variant}" are empty.`);
  }

  const phraseIds = new Set<string>();
  const grouped = new Map<string, number>();
  const familyKeyToPrimaryCount = new Map<string, number>();
  const familyKeyToRoles = new Map<string, Set<string>>();
  const familyKeyToTitle = new Map<string, string>();
  const familyKeyToRelated = new Map<string, string>();
  const familyIdToScenarioId = new Map<string, string>();
  const familyKeyToPrimaryAccessTier = new Map<string, 'starter' | 'premium'>();
  const familyKeyToAccessTiers = new Map<string, Set<'starter' | 'premium'>>();

  for (const phrase of phrases) {
    const requiredValues = [
      phrase.phrase_id,
      phrase.scenario_id,
      phrase.audio_key,
      phrase.english_text,
      phrase.target_text,
      phrase.pronunciation,
      phrase.context,
      phrase.emoji,
    ];

    if (requiredValues.some((value) => !value?.trim())) {
      throw new Error(`Phrase "${phrase.phrase_id || '<missing-id>'}" is missing required content.`);
    }

    if (!scenarioIds.has(phrase.scenario_id)) {
      throw new Error(`Phrase "${phrase.phrase_id}" references unknown scenario "${phrase.scenario_id}".`);
    }

    if (phraseIds.has(phrase.phrase_id)) {
      throw new Error(`Duplicate phrase ID "${phrase.phrase_id}" in "${variant}" draft.`);
    }

    phraseIds.add(phrase.phrase_id);
    grouped.set(phrase.scenario_id, (grouped.get(phrase.scenario_id) ?? 0) + 1);

    const familyId = normalizeFamilyId(phrase);
    const familyKey = `${phrase.scenario_id}:${familyId}`;
    const role = normalizeVariantRole(phrase.variant_role);
    const accessTier = normalizeAccessTier(phrase.access_tier);
    const familyRoles = familyKeyToRoles.get(familyKey) ?? new Set<string>();

    const previousScenarioId = familyIdToScenarioId.get(familyId);
    if (previousScenarioId && previousScenarioId !== phrase.scenario_id) {
      throw new Error(`Intent family ID "${familyId}" is reused across scenarios "${previousScenarioId}" and "${phrase.scenario_id}".`);
    }
    familyIdToScenarioId.set(familyId, phrase.scenario_id);

    if (familyRoles.has(role)) {
      throw new Error(`Intent family "${familyId}" in scenario "${phrase.scenario_id}" duplicates role "${role}".`);
    }

    familyRoles.add(role);
    familyKeyToRoles.set(familyKey, familyRoles);

    if (role === 'say-first') {
      familyKeyToPrimaryCount.set(familyKey, (familyKeyToPrimaryCount.get(familyKey) ?? 0) + 1);
      familyKeyToPrimaryAccessTier.set(familyKey, accessTier);
    }

    const familyTiers = familyKeyToAccessTiers.get(familyKey) ?? new Set<'starter' | 'premium'>();
    familyTiers.add(accessTier);
    familyKeyToAccessTiers.set(familyKey, familyTiers);

    if (phrase.family_title?.trim()) {
      const previousTitle = familyKeyToTitle.get(familyKey);
      if (previousTitle && previousTitle !== phrase.family_title.trim()) {
        throw new Error(`Intent family "${familyId}" in scenario "${phrase.scenario_id}" has inconsistent titles.`);
      }
      familyKeyToTitle.set(familyKey, phrase.family_title.trim());
    }

    if (phrase.related_family_id?.trim()) {
      const previousRelated = familyKeyToRelated.get(familyKey);
      if (previousRelated && previousRelated !== phrase.related_family_id.trim()) {
        throw new Error(
          `Intent family "${familyId}" in scenario "${phrase.scenario_id}" has inconsistent related_family_id values.`,
        );
      }
      familyKeyToRelated.set(familyKey, phrase.related_family_id.trim());
    }

    if (phrase.warning_note_type?.trim()) {
      normalizeWarningNoteType(phrase.warning_note_type);
    }

    if (phrase.audio_status?.trim()) {
      normalizeAudioStatus(phrase.audio_status);
    }
  }

  for (const quickPhraseId of plan.quickPhraseIds) {
    if (!phraseIds.has(quickPhraseId)) {
      throw new Error(`Quick phrase "${quickPhraseId}" is missing from "${variant}" draft.`);
    }
  }

  for (const scenario of plan.scenarios) {
    if (!grouped.has(scenario.id)) {
      throw new Error(`Scenario "${scenario.id}" is missing phrases in "${variant}" draft.`);
    }
  }

  for (const [familyKey, roles] of familyKeyToRoles.entries()) {
    if ((familyKeyToPrimaryCount.get(familyKey) ?? 0) !== 1) {
      throw new Error(`Intent family "${familyKey}" must contain exactly one "say-first" phrase.`);
    }

    if (!roles.has('say-first')) {
      throw new Error(`Intent family "${familyKey}" is missing a "say-first" phrase.`);
    }

    const primaryAccessTier = familyKeyToPrimaryAccessTier.get(familyKey);
    const familyTiers = familyKeyToAccessTiers.get(familyKey) ?? new Set<'starter' | 'premium'>();
    if (primaryAccessTier === 'premium' && familyTiers.has('starter')) {
      throw new Error(`Intent family "${familyKey}" strands starter content behind a premium primary.`);
    }
  }
}

function buildScenario(scenario: DraftScenario, draftPhrases: DraftPhrase[]) {
  const familyOrder = new Map<string, number>();
  const phraseOrder = new Map<string, number>();

  draftPhrases.forEach((phrase, index) => {
    phraseOrder.set(phrase.phrase_id, index);
    const familyId = normalizeFamilyId(phrase);
    if (!familyOrder.has(familyId)) {
      familyOrder.set(familyId, index);
    }
  });

  const phrases: BuiltPhrase[] = draftPhrases.map((phrase) => {
    const variantRole = normalizeVariantRole(phrase.variant_role);
    return {
      id: phrase.phrase_id,
      scenarioId: phrase.scenario_id,
      targetText: phrase.target_text,
      canonicalTargetText: phrase.canonical_target_text?.trim() || phrase.target_text,
      pronunciation: phrase.pronunciation,
      sourceText: phrase.english_text,
      audioKey: phrase.audio_key,
      accessTier: normalizeAccessTier(phrase.access_tier),
      context: phrase.context,
      usageNote: phrase.context,
      youMayHear: phrase.you_may_hear?.trim() || undefined,
      searchAliases: parseDelimitedList(phrase.search_aliases),
      intentFamilyId: normalizeFamilyId(phrase),
      variantRole,
      variantLabel: variantRoleToLabel(variantRole),
      warningNoteType: phrase.warning_note_type?.trim()
        ? normalizeWarningNoteType(phrase.warning_note_type)
        : undefined,
      audioStatus: normalizeAudioStatus(phrase.audio_status),
      emoji: phrase.emoji,
    };
  });

  const familyDrafts = new Map<
    string,
    {
      scenarioId: string;
      title: string;
      summary?: string;
      relatedFamilyId?: string;
      phrases: BuiltPhrase[];
    }
  >();

  for (const phrase of phrases) {
    const draftPhrase = draftPhrases.find((entry) => entry.phrase_id === phrase.id);
    if (!draftPhrase) {
      continue;
    }

    const familyId = phrase.intentFamilyId;
    const existing = familyDrafts.get(familyId);
    const title = draftPhrase.family_title?.trim() || draftPhrase.english_text.trim();
    const summary = draftPhrase.family_summary?.trim() || undefined;
    const relatedFamilyId = draftPhrase.related_family_id?.trim() || undefined;

    if (existing) {
      existing.phrases.push(phrase);
      continue;
    }

    familyDrafts.set(familyId, {
      scenarioId: phrase.scenarioId,
      title,
      summary,
      relatedFamilyId,
      phrases: [phrase],
    });
  }

  const intentFamilies = [...familyDrafts.entries()]
    .sort((left, right) => (familyOrder.get(left[0]) ?? 0) - (familyOrder.get(right[0]) ?? 0))
    .map(([familyId, family]) => {
      const orderedPhrases = [...family.phrases].sort((left, right) => {
        const roleDelta = getVariantRoleOrder(left.variantRole) - getVariantRoleOrder(right.variantRole);
        if (roleDelta !== 0) {
          return roleDelta;
        }

        return (phraseOrder.get(left.id) ?? 0) - (phraseOrder.get(right.id) ?? 0);
      });
      const primaryPhrase = orderedPhrases.find((phrase) => phrase.variantRole === 'say-first');

      if (!primaryPhrase) {
        throw new Error(`Intent family "${familyId}" is missing a "say-first" phrase.`);
      }

      return {
        id: familyId,
        scenarioId: family.scenarioId,
        title: family.title,
        summary: family.summary,
        relatedFamilyId: family.relatedFamilyId,
        accessTier: primaryPhrase.accessTier,
        primaryPhraseId: primaryPhrase.id,
        phraseIds: orderedPhrases.map((phrase) => phrase.id),
      };
    });

  return {
    id: scenario.id,
    name: scenario.name,
    emoji: scenario.emoji,
    description: scenario.description,
    tip: scenario.tip,
    intentFamilies,
    phrases: [...phrases].sort((left, right) => {
      const leftFamilyIndex = familyOrder.get(left.intentFamilyId) ?? 0;
      const rightFamilyIndex = familyOrder.get(right.intentFamilyId) ?? 0;

      if (leftFamilyIndex !== rightFamilyIndex) {
        return leftFamilyIndex - rightFamilyIndex;
      }

      const roleDelta = getVariantRoleOrder(left.variantRole) - getVariantRoleOrder(right.variantRole);
      if (roleDelta !== 0) {
        return roleDelta;
      }

      return (phraseOrder.get(left.id) ?? 0) - (phraseOrder.get(right.id) ?? 0);
    }),
  };
}

function intentFamilyCount(scenarios: Array<{ intentFamilies: Array<unknown> }>) {
  return scenarios.reduce((total, scenario) => total + scenario.intentFamilies.length, 0);
}

function phraseCount(scenarios: Array<{ phrases: Array<unknown> }>) {
  return scenarios.reduce((total, scenario) => total + scenario.phrases.length, 0);
}

function resolveOutputPath(output: string) {
  return path.isAbsolute(output) ? output : path.resolve(APP_ROOT, output);
}

function normalizeVariant(value?: string) {
  return value?.trim().toLowerCase();
}

function normalizeAccessTier(value?: string): 'starter' | 'premium' {
  const normalizedValue = value?.trim().toLowerCase();

  if (!normalizedValue) {
    return 'starter';
  }

  if (normalizedValue === 'starter' || normalizedValue === 'premium') {
    return normalizedValue;
  }

  throw new Error(`Unsupported access tier "${value}". Expected "starter" or "premium".`);
}

function normalizeVariantRole(value?: string): DraftVariantRole {
  const normalizedValue = value?.trim().toLowerCase() as DraftVariantRole | undefined;

  if (!normalizedValue) {
    return 'say-first';
  }

  if (
    normalizedValue === 'say-first' ||
    normalizedValue === 'more-polite' ||
    normalizedValue === 'clearer' ||
    normalizedValue === 'also-common'
  ) {
    return normalizedValue;
  }

  throw new Error(
    `Unsupported variant role "${value}". Expected "say-first", "more-polite", "clearer", or "also-common".`,
  );
}

function normalizeWarningNoteType(value?: string): DraftWarningNoteType {
  const normalizedValue = value?.trim().toLowerCase() as DraftWarningNoteType | undefined;

  if (
    normalizedValue === 'formal' ||
    normalizedValue === 'bookish' ||
    normalizedValue === 'harder-to-say' ||
    normalizedValue === 'recognition-only'
  ) {
    return normalizedValue;
  }

  throw new Error(
    `Unsupported warning note type "${value}". Expected "formal", "bookish", "harder-to-say", or "recognition-only".`,
  );
}

function normalizeAudioStatus(value?: string): DraftAudioStatus {
  const normalizedValue = value?.trim().toLowerCase() as DraftAudioStatus | undefined;

  if (!normalizedValue) {
    return 'ready';
  }

  if (normalizedValue === 'ready' || normalizedValue === 'planned') {
    return normalizedValue;
  }

  throw new Error(`Unsupported audio status "${value}". Expected "ready" or "planned".`);
}

function normalizeFamilyId(phrase: DraftPhrase) {
  return phrase.family_id?.trim() || phrase.phrase_id;
}

function getVariantRoleOrder(role?: DraftVariantRole) {
  switch (role) {
    case 'say-first':
      return 0;
    case 'more-polite':
      return 1;
    case 'clearer':
      return 2;
    case 'also-common':
      return 3;
    default:
      return 4;
  }
}

function variantRoleToLabel(role?: DraftVariantRole) {
  switch (role) {
    case 'more-polite':
      return 'More polite';
    case 'clearer':
      return 'Clearer';
    case 'also-common':
      return 'Also common';
    case 'say-first':
    default:
      return 'Say this first';
  }
}

function parseDelimitedList(value?: string) {
  const items = value
    ?.split('|')
    .map((item) => item.trim())
    .filter(Boolean);

  return items?.length ? items : undefined;
}

function toIdentifier(value: string) {
  const parts = value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.toLowerCase());

  if (!parts.length) {
    throw new Error(`Cannot convert variant "${value}" into an identifier.`);
  }

  return parts
    .map((part, index) => (index === 0 ? part : `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`))
    .join('');
}

function parseArgs(argv: string[]): CliArgs {
  const parsed: CliArgs = {};

  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    const next = argv[index + 1];

    if (token === '--variant') {
      parsed.variant = next;
      index += 1;
      continue;
    }

    if (token === '--output') {
      parsed.output = next;
      index += 1;
      continue;
    }

    throw new Error(`Unknown argument "${token}".`);
  }

  return parsed;
}

function parseCsv(text: string) {
  const normalizedText = text.replace(/^\uFEFF/, '');
  const lines = normalizedText
    .split(/\r?\n/)
    .filter((line) => line.trim().length > 0);

  if (!lines.length) {
    return [];
  }

  const headers = parseCsvLine(lines[0]);

  return lines.slice(1).map((line) => {
    const values = parseCsvLine(line);
    return Object.fromEntries(headers.map((header, index) => [header, values[index] ?? '']));
  });
}

function parseCsvLine(line: string) {
  const cells: string[] = [];
  let current = '';
  let inQuotes = false;

  for (let index = 0; index < line.length; index += 1) {
    const character = line[index];
    const next = line[index + 1];

    if (character === '"') {
      if (inQuotes && next === '"') {
        current += '"';
        index += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (character === ',' && !inQuotes) {
      cells.push(current);
      current = '';
      continue;
    }

    current += character;
  }

  cells.push(current);
  return cells;
}

void main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
